### PR TITLE
Remove elixir tests from Makefile "check" target

### PR DESCRIPTION
**Pull request by jaydoane**
## Overview

The elixir tests are by far the flakiest tests in the entire suite. In
the interest of being able to merge changes to master without having to
retry over several days, temporarily disable elixir tests from running
via `make check`.

## Testing recommendations

```
make check
```
should not run the elixir test suite

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by garrensmith** [comment]
Is it all the tests failing consistently or some of the tests failing consistently? I would prefer we rather ignore specific tests until we have a consistent set of elixir tests. We can then try and make the other ones more consistent.

**Comment by jaydoane** [comment]
> Is it all the tests failing consistently or some of the tests failing consistently? I would prefer we rather ignore specific tests until we have a consistent set of elixir tests. We can then try and make the other ones more consistent.

I've only been keeping an eye on the builds for the last few days, but there are _many_ tests that fail occasionally, and a small handful that tend to fail more regularly. I think it will be a long and painful exercise to selectively ignore the worst offenders, since right now making _any_ change on master often requires days worth of build restarts.

**Comment by rnewson** [comment]
I'm +1 on this and, for me, the criteria to restore it is when it has parity with the javascript test suite, which would be removed from `make check` in the same commit as elixir test is added.

**Comment by nickva** [comment]
For EUnit tests we have up to 3 retries for individual apps when one fails. There are retries but EUnit tests usually end up passing.

Would it be easy to do that for Elixir tests as well? Ideally we'd do it per test case, but per-suite or app might work as well.

Another observation is that Elixir tests run with 3 couch nodes, while Javascript tests with only one. On one hand it is a more realistic integration test, on the other, perhaps the extra two nodes is too much for Travis CI environment to handle and we can use one node there as well.

**Comment by wohali** [comment]
@nickva if you are willing to put up a 3x PR we can try it.

Travis is no longer the target; this is failing repeatedly on our new Jenkins setup (which is still in alpha, until Infra gets our GitHub hooks setup.) The Jenkins nodes are in the IBM Cloud.

**Comment by garrensmith** [comment]
https://github.com/apache/couchdb/pull/2363 Changes the elixir tests to run with `n =1`. I would like to merge that in first before we resort to pulling the tests out completely

**Comment by garrensmith** [comment]
Closing because of #2363

**Pull request closed without merging**
