### PR TITLE
Document _versions endpoint

### PR DESCRIPTION
**Pull request by big-r81**
Document undocumented _versions endpoint.

### CODE REVIEW

**Review by nickva — APPROVED** [review]

**Comment by nickva** [comment]
Good first test of a fast docs-only CI run!

Screen Shot 2022-09-09 at 10 18 42 AM

**Comment by nickva** [comment]
@big-r81 should we merge this?

**Comment by big-r81** [comment]
@nickva 
Of course, can you check why the CI is failing? Am on vacation…

**Comment by nickva** [comment]
@big-r81 ah no worries, enjoy your vacation.

The issue is the json document is not regular json and the latest sphinx does check that

It doesn't like this part:
```
                    "sha256",
                    ...
                ]
```

I'll fix it and merge it.

**Pull request merged**
