### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by iilyak**
Update dependencies to fix CI failures for `couchdb-couch` (and possibly others) repository.

### CODE REVIEW

**Comment by eiri** [comment]
+1

**Comment by nickva** [comment]
@iilyak should we bump replicator dep as well

**Comment by iilyak** [comment]
@nickva: The couch_replicator's sha matching the master already.

**Comment by nickva** [comment]
@iilyak sorry, missed it, it was under "Type spec fixes" part.

+1

**Pull request merged**
