### PR TITLE
Port prometheus 3.x

### PR DESCRIPTION
**Pull request by tonysun83**
## Overview

This is a port of https://github.com/apache/couchdb/pull/3416.

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by wohali** [comment]
@tonysun83 

1. Is it enabled or disabled by default? Looks like enabled and bound to 127.0.0.1:17986 by default, is this accurate?
2. Is this disable-able at all?
3. Can you write some docs for this? I see no mention of this functionality anywhere in apache/couchdb-documentation. I can't really release this as a new exciting in feature in 3.2 without something in the docs.

Thanks,
Joan

**Comment by tonysun83** [comment]
@wohali 

1) + 2) The additional port/mochiweb server is disabled by default, but the ability to return prometheus metrics via the traditional 5984 port is always on.
3) Ya I can write this up tomorrow.

**Comment by tonysun83** [comment]
@wohali  I've added documentation PR here: https://github.com/apache/couchdb-documentation/pull/660 I need to clean some things up as the build is failing but let me know in terms of content if I'm missing anything you'd like me to add.

**Comment by wohali** [comment]
@tonysun83 Thanks for the work here. Looking generally good, left my comments over there. If you can address the remaining documentation gaps this is +1.

**Pull request merged**
