### PR TITLE
Smoosh update operator guide to use rpc:multicall

### PR DESCRIPTION
**Pull request by chewbranca**
## Overview

The smoosh `operator_guide.md` has been updated to use rpc:multicall in the examples. The previous examples used a library not included in CouchDB for some of the rpc commands.

## Checklist

- [ ] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Review by nickva — APPROVED** [review]
+1

Don't forget to add this to 3.x. In `main` (future 4.x) we don't run smoosh or have connected nodes. However, in the meantime it doesn't hurt to keep main in sync with 3.x.

**Comment by wohali** [comment]
Yeah I would simply at this point merge this to `3.x` only, not `main`.

**Comment by bessbd** [comment]
@chewbranca : should we merge this?

**Comment by nickva** [comment]
I'll merge it since it got a green pass on CI

**Pull request merged**
