### PR TITLE
Restrict design doc update methods

### PR DESCRIPTION
**Pull request by jaydoane**
## Overview

Documentation for design doc update functions specifies that permitted
methods are:

    POST /{db}/_design/{ddoc}/_update/{func}
    PUT /{db}/_design/{ddoc}/_update/{func}/{docid} [2]

But currently anything is accepted, even bogus methods such as in the
following example work:

```
$ curl -v -u adm localhost:15984/db-1/_design/ddoc/_update/change -X BOGUS

> BOGUS /db-1/_design/bar/_update/change HTTP/1.1
>
< HTTP/1.1 200 OK
< content-length: 11
< content-type: text/html; charset=utf-8
<
* Connection #0 to host localhost left intact
Empty World* Closing connection 0
```

A strict reading of the docs indicates that the null document endpoint
only allows POST [1] while the endpoint taking a document id only
allows PUT [2]. However, the examples in both cases exclusively use
POST, and also PUT doesn't make as much sense from a semantic
perspective since a new resource isn't being created, I assume the PUT
 is a typo, and both should be changed to POST.

However, given the inconsistent usage even in CouchDB's own test
suite, it seems prudent to minimize incompatibility, while still
imposing reasonable restrictions, and allow either PUT or POST for
both endpoints.

[1] https://docs.couchdb.org/en/latest/api/ddoc/render.html#post--db-_design-ddoc-_update-func
[2] https://docs.couchdb.org/en/latest/api/ddoc/render.html#put--db-_design-ddoc-_update-func-docid

## Testing recommendations

```
make check
```

## Related Issues or Pull Requests

https://github.com/apache/couchdb-documentation/pull/674

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [x] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Review by iilyak — APPROVED** [review]
+1

**Comment by rnewson** [comment]
hm, not sure here. the _show / _list / _update handlers exist to allow users to decide their own semantics, so allowing any http method for _update makes sense (e.g, PATCH).

**Comment by rnewson** [comment]
"any except GET", rather.

**Comment by nickva** [comment]
Added a comment related to this on the docs PR https://github.com/apache/couchdb-documentation/pull/674#issuecomment-900463236

**Comment by jaydoane** [comment]
> hm, not sure here. the _show / _list / _update handlers exist to allow users to decide their own semantics, so allowing any http method for _update makes sense (e.g, PATCH).

@rnewson if that's the intention, the documentation doesn't make it clear, since it specifies [PUT](https://docs.couchdb.org/en/latest/api/ddoc/render.html#put--db-_design-ddoc-_update-func-docid) and [POST](https://docs.couchdb.org/en/latest/api/ddoc/render.html#post--db-_design-ddoc-_update-func), but no others. So, maybe we just need to improve the docs?

**Comment by rnewson** [comment]
In this case I think the docs are wrong.

I don't think changing the behaviour of _update is warranted without a major version bump unless there is a security issue at play here that has not yet been mentioned.

As _update handlers go away in the next version (4.0) I think, at most, a doc fix is appropriate, not a compatibility-breaking change.

**Comment by rnewson** [comment]
-1.

**Comment by jaydoane** [comment]
> As _update handlers go away in the next version (4.0) I think, at most, a doc fix is appropriate, not a compatibility-breaking change.

Ah, I was not aware update functions are deprecated! Unlike [list](https://docs.couchdb.org/en/latest/api/ddoc/render.html#db-design-design-doc-list-list-name-view-name) and [show](https://docs.couchdb.org/en/latest/api/ddoc/render.html#db-design-design-doc-show-show-name) functions, update functions are not currently annotaged as deprecated.

**Comment by rnewson** [comment]
@janl double check me on _update deprecation?

**Pull request closed without merging**
