### PR TITLE
Enable test suite functions in the test suite

### PR DESCRIPTION
**Pull request by davisp**
This enables the new couchjs test suite functions.

COUCHDB-3057

---

screen shot 2016-07-12 at 3 49 04 pm

### CODE REVIEW

**Comment by rnewson** [comment]
+1

**Comment by rnewson** [comment]
could you also do the change to wait(ms) function?

**Comment by rnewson** [comment]
``` function wait(ms) {
-  var t0 = new Date(), t1;
-  do {
-    CouchDB.request("GET", "/");
-    t1 = new Date();
-  } while ((t1 - t0) <= ms);
+  sleep(ms);```

**Comment by davisp** [comment]
Your diff did not render so hot

**Comment by rnewson** [comment]
my hotness made it look not so hot but both are pretty hot

**Pull request merged**
