### PR TITLE
build: support OTP-19.0 for 1.6.x

### PR DESCRIPTION
**Pull request by gmile**

### CODE REVIEW

**Comment by kxepal** [comment]
@gmile Nice! Thanks for contribution. Could you also update `.travis.yml` to make sure that we really build green with Erlang 19 there? Worth to add 18.3 as well there too.

**Comment by gmile** [comment]
@kxepal sure! Just pushed a commit with updated `.travis.yml` config, we'll know if all good in an hour and a half

**Comment by gmile** [comment]
@kxepal yeah, so it appears build is broken with `18.3` and `19.0`, although it compiling couchdb 1.6.1 against `19.0` from OS X worked locally.

I'm looking at the [log for failed 19.0 build](https://api.travis-ci.org/jobs/143818532/log.txt?deansi=true) right now. Can you spot the problem?

**Comment by gmile** [comment]
I'll stop the current build on CI, comment out 17.0, R16B03-1, R15B03, R14B04 and will try to see what's going on here with 18.3 and 19.0.

**Comment by kxepal** [comment]
It's because `erlang-19.0-nonroot.tar.bz2` file:
```
make[2]: Leaving directory `/home/travis/build/apache/couchdb/share/doc/build'
grep -rL 'http://www.apache.org/licenses/LICENSE-2.0' * \
	    | grep --include= -vEf ./license.skip; \
	    test "$?" -eq 1
erlang-19.0-nonroot.tar.bz2
make[1]: *** [distcheck-hook] Error 1
make[1]: Leaving directory `/home/travis/build/apache/couchdb'
make: *** [distcheck] Error 1

travis_time:end:1e319b60:start=1468221103840995910,finish=1468221155385200274,duration=51544204364
[0K
[31;1mThe command "make distcheck" exited with 2.[0m
```

During Erlang 19 installation, Travis puts that file into source tree. At the same time distcheck checks all the files for license header and fails because this one is not expected and it's not in blacklist.

I remember I fixed once upon a time that issue, but not sure where now. Simple action would be to remove that archive before build starts IIRC. This should help.

**Comment by gmile** [comment]
@kxepal how about adding a line `^erlang-19.0-nonroot.tar.bz2` line to `https://github.com/apache/couchdb/blob/master/license.skip`? It seems even easier, unless you would prefer not to populate the blacklist with version-specific files

**Comment by kxepal** [comment]
@gmile 
It will not ~web~scale well and we have to maintain that list for every Erlang release on Travis. I think `rm erlang-*.tar.bz2` would be simpler solution and won't obligate to do any else actions in nearest future.

**Comment by gmile** [comment]
@kxepal no problem at all, will do that. Thanks for helping with this!

**Comment by kxepal** [comment]
Great! Thanks! Let's wait for Travis now (:

**Comment by gmile** [comment]
@kxepal something's still not right, but this time it's vise-versa: builds for 19.0 and 18.3 have passed, but all others have failed. Maybe this gives any clue regarding an old fix you've mentioned?:

> I remember I fixed once upon a time that issue, but not sure where now.

**Comment by gmile** [comment]
Probably this fails now:

```
The command "rm erlang-*.tar.bz2" exited with 1
```

**Comment by kxepal** [comment]
@gmile Hm, right. Probably I used `rm -f` which always returns success whenever file exists or not.

**Comment by gmile** [comment]
@kxepal and it's green, finally

**Comment by kxepal** [comment]
@dch you miss something here

**Comment by dch** [comment]
@gmile just pointed this out to me -- I checked jira but not here. I'm really sorry for jumping your PR. I can either revert my 2 direct commits to the 1.6.x branch or merge yours in on top, with credit of course. @gmile which would you prefer?

**Comment by gmile** [comment]
@dch no worries, no offence taken! Please go ahead with whichever path suites you, you're the maintainer after all :)

**Comment by gmile** [comment]
@dch I _think_ it should be less work to revert + apply this PR. Otherwise you'll have to cherry-pick changes, such as `.travis.yml`?

**Comment by kxepal** [comment]
I think indeed we can cherry pick patches for .travis.yml and do merge on 1.x.x branch. What do you think @dch @gmile ?

**Comment by gmile** [comment]
Besides, I think this is missing from @dch's patch – https://github.com/apache/couchdb/pull/431/commits/98ff0acdf04a8f0f29d066ae33f6e7332c024da9#diff-67e997bcfdac55191033d57a16d1408aR441 (though I can't really say how important this is)

**Comment by dch** [comment]
I'll revert & apply, it will make a cleaner merge to 1.x.x for future. @gmile I'll tweak this line in `configure.ac` if that's ok:

```
+erlang_version_error="The installed Erlang version must be >= R14B (erts-5.8.1) and =< 19 (erts-8.0)"
```

as that's actually what the code checks for. I grabbed this diff from the last time I did this for the FreeBSD port and it doesn't have the `configure.ac` check in it as it pulls from the tarball. Shame on me...

**Comment by gmile** [comment]
@dch good to know!

>  I'll tweak this line in configure.ac if that's ok:

Sure, go ahead and change that line. Just to clarify, I tested using `19.0.1`, which yields `erts-8.0.1`:
image

**Comment by dch** [comment]
thanks @gmile & congrats on your first contribution to Apache CouchDB :-)

**Comment by gmile** [comment]
@dch haha, thank you! :)

**Comment by gmile** [comment]
@dch now that this was merged, will there be a point release in 1.6.x branch? If not right now, are you planning to make one in future?

**Comment by dch** [comment]
good question, do you want to ask this on the dev list? we have a nice 1.x.x branch (your 2nd commit, well done!) which has improved SSL amongst other things, maybe that is a better option. OTOH 2.0 is arguably more important atm but it should be possible to do both.

**Comment by gmile** [comment]
> we have a nice 1.x.x branch

Ah I missed that, nice!

> good question, do you want to ask this on the dev list?

Sure! Can you share the link to dev list please?

@dch reason I'm asking is because I'm trying to update the [recipe](https://github.com/gmile/homebrew-core/blob/master/Formula/couchdb.rb) on homebrew. It appears so that all homebrew users are stuck with 1.6.1 forever (more than a year now). I do see an [old commit](https://github.com/Homebrew/homebrew-core/commit/5cefb216b27d60772738458e9af411710676ccd4#diff-ccdcb18cac44281832236416670515d9R10) from yours fixing support for erlang R18.0 and all I wanted is to expand support to 19.0 as well.

I was hoping to update the couchdb recipe so that it'd unblock another issue, related to upgrading Erlang recipe on homebrew to 19.0. There's an evidence that updating erlang will break current couchdb 1.6.1 installation on homebrew.

I saw a few options to resolve the issue with erlang recipe:

1. update the text of your patch directly (which I did in https://github.com/Homebrew/homebrew-core/pull/2891) (it kind of feels wrong and dishonest to update someone's code, given your credentials in that patch, but if it's OK with you – maybe it's a way forward?),
2. do it _the proper way_™, and patch the 1.6.x branch first, and then override the text of your patch with the text on my patch, including overriding the credentials (this didn't work, see last edit to [this comment](https://github.com/Homebrew/homebrew-core/pull/2891#issuecomment-231862749)),
3. do it even more proper way, tag a latest stable 1.x.x (1.6.x?) release, and cleanup homebrew recipes accordingly.

**Pull request closed without merging**
