### PR TITLE
ci(mac): re-enable mac CI for the full build

### PR DESCRIPTION
**Pull request by janl**
## Checklist

- [ ] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] Documentation changes were made in the `src/docs` folder
- [ ] Documentation changes were backported (separated PR) to affected branches

### CODE REVIEW

**Comment by nickva** [comment]
Use the `jenkins-*`-like branch name so the full CI will run on the PR. That's a good way to test full CI changes in a PR.

**Review by big-r81 — APPROVED** [review]
+1

**Review by nickva — CHANGES_REQUESTED** [review]
Thanks for enabling macos again, Jan.

I tried my suggestion building the full CI and see that it failed https://github.com/apache/couchdb/pull/4389


https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/jenkins-ci-enable-mac/1/pipeline/80

```
[2023-01-18T19:06:28.709Z] + ./configure --skip-deps --spidermonkey-version 91

[2023-01-18T19:06:28.709Z] ./configure: line 36: erl: command not found

script returned exit code 127
```

**Comment by janl** [comment]
PATH issue, thanks!

**Review by nickva — APPROVED** [review]
Screen Shot 2023-01-19 at 12 23 39 PM

Well done +1

**Pull request merged**
