### PR TITLE
Use fabric to get design docs in the compaction daemon

### PR DESCRIPTION
**Pull request by nickva**
Previously the compaction daemon looked for design docs in each shard file.
This worked well for versions < 2.x, however, for clustered databases design
documents will only be found in their respective shards based on the document
id hashing algorithm. This meant that in a default setup of Q=8 only the views
of one shard range, where the _design document lives, would be compacted.

The fix for this issue is to use fabric to retrive all the design documents for
clustered database.

Issue #1579

### CODE REVIEW

**Comment by eiri** [comment]
This is what I was thinking about: https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db_engine.erl#L1003-L1023

Should we just export it and use here to DRY thing s a bit?

**Comment by nickva** [comment]
@eiri Even more fun couch_db also has this as well:

https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db.erl#L611-L620

Though slightly different.

Also noticed that the current local node design doc getter ignores deleted document not sure if the other two do that...

**Comment by eiri** [comment]
Huh, a double deja vu! One in couch_db even exported, so we can use it here and one in `bt` is probably some sort of purge related hack kept separate to avoid cross referencing.

Good catch on that ignore on deleted design docs! I totally missed it when was fixing `_design_docs` handler, we'll need to remediate it as well.

**Comment by nickva** [comment]
@eiri I used couch_db's get_design docs. It simplified things quite a bit, so that was nice find, thanks!

Regarding deleted docs, design_docs doesn't set include deleted filter so deleted docs shouldn't appear in the results so no need to handle that case.

**Pull request merged**
