### PR TITLE
Clean elixir build artifacts with `make clean`

### PR DESCRIPTION
**Pull request by jaydoane**
## Overview

Stale Elixir dependencies can cause test failures after upgrading Erlang or Elixir, so remove them whenever we `make clean`.

## Testing recommendations

Confirm it removes Elixir test artifacts.
```
❯ mix deps.compile

❯ tree -L 3 _build/
_build/
└── dev
    └── lib
        ├── b64url
        ├── bunt
        ├── couchdbtest
        ├── credo
        ├── file_system
        ├── httpotion
        ├── ibrowse
        ├── jason
        ├── jiffy
        ├── junit_formatter
        ├── jwtf
        └── ssl_verify_fun

15 directories, 0 files

❯ make clean

❯ tree -L 3 _build/
_build/

0 directories, 0 files
```

## Checklist

- [x] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] Documentation changes were made in the `src/docs` folder
- [ ] Documentation changes were backported (separated PR) to affected branches

### CODE REVIEW

**Review by nickva — APPROVED** [review]
+1 if the full CI passes (make a `jenkins-...` branch and use a `git commit amend --no-edit` to give it a new commit ID and push, no need for a PR even).

Mainly because previously we had some issues with elixir + clean not working: https://github.com/apache/couchdb/pull/4740

**Comment by big-r81** [comment]
Don’t forget to update`Makefile.win` 😉

**Comment by jaydoane** [comment]
> +1 if the full CI passes (make a `jenkins-...` branch and use a `git commit amend --no-edit` to give it a new commit ID and push, no need for a PR even).
> 
> Mainly because previously we had some issues with elixir + clean not working: #4740

I updated `Makefile.win` and ran the full CI [here](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/jenkins-make-clean-elixir-test-deps/1/pipeline) and it seems to pass.

Is it possible that whatever was causing https://github.com/apache/couchdb/issues/4706 has been fixed, and this is now safe to merge?

**Comment by nickva** [comment]
Thanks, Jay. Let’s merge it!

**Pull request merged**
