### PR TITLE
Support specifying individual Elixir tests to run

### PR DESCRIPTION
**Pull request by iilyak**
## Overview

Introduction of an Elixir based integration tests is a great thing. This PR adds an ability to run tests individually from a Makefile. Similar to the way we do it with eunit. 

Individual tests can be specified as:

- `make elixir tests=test/basics_test.exs`
- `make elixir tests=test/basics_test.exs,test/config_test.exs`
- `make elixir tests=test/basics_test.exs:17`

### on UNIX

```
make elixir tests=test/basics_test.exs
make elixir tests=test/basics_test.exs,test/config_test.exs
make elixir tests=test/basics_test.exs:17
```

### on Windows

```
make elixir tests=test\basics_test.exs
make elixir tests=test\basics_test.exs,test\config_test.exs
make elixir tests=test\basics_test.exs:17
```

## Related Issues or Pull Requests

N/A

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by eiri** [comment]
Looks good, but `Makefile.win` also needs same updating

**Comment by iilyak** [comment]
Win doesn't have `sed` so we need to find another solution.

**Comment by eiri** [comment]
You wouldn't need `sed` if you'd just reuse $(suites) from`javascript` target and run it as

```
make elixir suites=test/basics_test.exs
make elixir suites="test/basics_test.exs test/reduce_test.exs"
```

**Comment by iilyak** [comment]
@eiri I re-implemented the feature differently. Hopefully it works for win, I don't have access to windows to test it.

**Comment by iilyak** [comment]
@eiri: Let me know if I should rename `tests` into `suites` I cannot make up my mind.

**Comment by eiri** [comment]
@iilyak I don't have preferences for opt name, both used in eunit tests. A side note - can you, please, not force-push PRs in review? I've got a merge conflict when pulled your update.

@wohali Can you please test the Windows part of this PR? The UNIX side works fine.

**Comment by wohali** [comment]
@eiri I'm seeing merge conflicts, can you resolve those first please?

mwsnap-046

**Comment by eiri** [comment]
@wohali this is not my PR. @iilyak can you address this, please?

**Comment by iilyak** [comment]
@wohali I re-based to fix conflicts
@eiri Had to push force to fix conflicts again.

**Comment by van-mronov** [comment]
Hi all! May I ask something?

`mix` already provides ability to run only tests marked with some tag. Also, `@moduletag` module attribute adds its value as a tag for all tests  from this module.

For example, `test/basics_test.exs` defines `@moduletag :basics`.
So if you want to run only tests from this module you can do it by `mix test --only basics`.

Does current implementation of Makefile support running tests like `make elixir --only basics`?

**Comment by eiri** [comment]
@van-mronov This is what this PR is about. It adds an option `tests` to `make elixir` target that passed further to `mix test`.

**Comment by van-mronov** [comment]
@eiri yeah, I mean if pass `--only basics` to `tests` option will it pass further as `mix test --only basics`?

**Comment by eiri** [comment]
I don't know, but by a look at the code I don't see why it wouldn't. Try to check out this branch and just try it?

**Comment by wohali** [comment]
@iilyak sorry for the delay, I've been getting Jenkins/FreeBSD working again. I'll be able to look at this tomorrow.

**Comment by iilyak** [comment]
@wohali the credo checks complains on master as well. Fixing it would involve porting over more tests from JavaScript test suites (all TODOs are about porting more tests).

**Comment by wohali** [comment]
@iilyak then +1 from me!

**Pull request merged**
