### PR TITLE
Pass user_ctx in _bulk_get

### PR DESCRIPTION
**Pull request by rnewson**
This fixes _bulk_get for _users db and probably others I don't know

### CODE REVIEW

**Comment by davisp** [comment]
+1

**Comment by nickva** [comment]
chttpd_db_bulk_get_test eunit failure

**Comment by adv4000** [comment]
I hope it also will fix  **_metadata** db along with  **_users** db

**Comment by wohali** [comment]
@adv4000 CouchDB doesn't currently do anything with the _metadata DB, what are you expecting to find there?

**Comment by adv4000** [comment]
Issue reported on couchdbbackup tool: https://github.com/cloudant/couchbackup/issues/253
Looks like _bulk_get not working with databases named **_users** and **_metadata**

**Pull request merged**
