### PR TITLE
Simplify regression test for COUCHDB-1283

### LINKED ISSUE #680: EUnit: couchdb_1283: View group shutdown fails
Hey @davisp we still have issues in couchdb_1283.

* https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/94/pipeline
  * https://couchdb-vm2.apache.org/ci_errorlogs/jenkins-couchdb-94-2017-07-14T16:50:13.852436/couchlog.tar.gz
Makefile output:

```
View group shutdown
    couchdb_views_tests:315: couchdb_1283...*failed*
in function couchdb_views_tests:wait_for_process_shutdown/3 (test/couchdb_views_tests.erl, line 420)
in call from couchdb_views_tests:'-couchdb_1283/0-fun-21-'/0 (test/couchdb_views_tests.erl, line 365)
**error:{assertion_failed,[{module,couchdb_views_tests},
                   {line,422},
                   {reason,"Failure waiting for db shutdown"}]}
  output:<<"">>
```

couch.log:
```
[info] 2017-07-14T16:50:03.368819Z nonode@nohost <0.20932.1> -------- Apache CouchDB has started on http://127.0.0.1:46375/
[notice] 2017-07-14T16:50:03.369155Z nonode@nohost <0.20784.1> -------- config: [compactions] _default deleted for reason nil
[info] 2017-07-14T16:50:03.369202Z nonode@nohost <0.7.0> -------- Application couch started on node nonode@nohost
[notice] 2017-07-14T16:50:03.369958Z nonode@nohost <0.20784.1> -------- config: [couchdb] max_dbs_open set to 3 for reason nil
[notice] 2017-07-14T16:50:03.371239Z nonode@nohost <0.20784.1> -------- config: [couchdb] delayed_commits set to false for reason nil
[info] 2017-07-14T16:50:03.643758Z nonode@nohost <0.20916.1> -------- alarm_handler: {set,{system_memory_high_watermark,[]}}
[info] 2017-07-14T16:50:03.853451Z nonode@nohost <0.21012.1> -------- Opening index for db: eunit-test-db-150051003375857 idx: _design/foo sig: "0963a19eb3ef007218f1e11f0aefa2d9"
[info] 2017-07-14T16:50:03.853818Z nonode@nohost <0.21015.1> -------- Starting index update for db: eunit-test-db-150051003375857 idx: _design/foo
[info] 2017-07-14T16:50:03.928889Z nonode@nohost <0.21015.1> -------- Index update finished for db: eunit-test-db-150051003375857 idx: _design/foo
[notice] 2017-07-14T16:50:03.929427Z nonode@nohost <0.20952.1> -------- 127.0.0.1 - - GET /eunit-test-db-150051003375857/_design/foo/_view/foo 200
[error] 2017-07-14T16:50:05.045951Z nonode@nohost <0.21016.1> -------- gen_server <0.21016.1> terminated with reason: killed
  last msg: {'EXIT',<0.21012.1>,killed}
     state: {st,<0.21012.1>,couch_mrview_index,undefined}
[error] 2017-07-14T16:50:05.046769Z nonode@nohost <0.21016.1> -------- CRASH REPORT Process  (<0.21016.1>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_compactor,init,['Argument__1']}, ancestors: [<0.21012.1>,<0.21011.1>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 27, reductions: 119
[error] 2017-07-14T16:50:05.047722Z nonode@nohost <0.21015.1> -------- gen_server <0.21015.1> terminated with reason: killed
  last msg: {'EXIT',<0.21012.1>,killed}
     state: {st,<0.21012.1>,couch_mrview_index,undefined}
[error] 2017-07-14T16:50:05.048419Z nonode@nohost <0.21015.1> -------- CRASH REPORT Process  (<0.21015.1>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_updater,init,['Argument__1']}, ancestors: [<0.21012.1>,<0.21011.1>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 1690
[info] 2017-07-14T16:50:05.049159Z nonode@nohost <0.7.0> -------- Application couch exited with reason: stopped
[info] 2017-07-14T16:50:05.049365Z nonode@nohost <0.20916.1> -------- alarm_handler: {clear,system_memory_high_watermark}
[info] 2017-07-14T16:50:05.051419Z nonode@nohost <0.7.0> -------- Application os_mon exited with reason: stopped
```

### PR DESCRIPTION
**Pull request by davisp**
The previous version of this test relied on trying to bump into the
all_dbs_active error from the couch_server LRU. This proves to be rather
difficult to reliably provide assertions on behavior. In hindsight all
we really care about is that the compactor holds a monitor against the
database and then we can trust couch_server will not evict anything that
is actively monitored.

Fixes #680

### CODE REVIEW

**Comment by wohali** [comment]
Lots of errors in Travis here, can you take a look?

**Comment by davisp** [comment]
Nothing related to this change.

These three jobs are instances of #687

* https://travis-ci.org/apache/couchdb/jobs/254582139
* https://travis-ci.org/apache/couchdb/jobs/254582142
* https://travis-ci.org/apache/couchdb/jobs/254581858

And then this error that I'll look into:

* https://travis-ci.org/apache/couchdb/jobs/254581856

```
module 'couch_log_server_test'
  couch_log_server_test: couch_log_server_test_...*timed out*
  undefined
```

**Comment by nickva** [comment]
+1

**Comment by davisp** [comment]
Looks like I've fixed the mango/mem3 interaction. Re-running these tests now.

**Comment by davisp** [comment]
And I totally forgot to rebase it onto master before restarting the tests... lets try that again.

**Comment by davisp** [comment]
All green.

**Pull request merged**
