### PR TITLE
Allow couchspawnkillable to live in directories with spaces

### PR DESCRIPTION
**Pull request by jerem**
Ref #991.
Inspired by https://github.com/apache/couchdb/commit/f122f94291bfbc87496efca3c04540bb190b985a

### CODE REVIEW

**Comment by dch** [comment]
moving discussion from #991. I'm fine to merge this, I'll do some manual checks on UNIX to
ensure we don't break stuff. 

The bigger question is, do we want to roll a 1.7.2, or (my preference), do I simply include this as a diff
into the windows build?

I'd like a few +1 on this.

**Comment by wohali** [comment]
I don't personally mind you rolling this into the 1.7.1 windows build but you need to clearly document the patch has been applied, since then it's not strictly a 1.7.1 convenience build. Have you tested that it does the right thing?

-1 on a 1.7.2 release just for this.

Would like to see something similar land on master for 2.x, but need thorough testing there to see if we can't move ourselves back under `C:\Program Files\` or not. There may be other issues than just this one, esp. with the `data` directory.

**Comment by nickva** [comment]
@wohali we do have it in master for couch_os_process like @jerem linked to but we don't have it for couch_os_daemons interestingly enough. I think we'd want it for both 

https://github.com/apache/couchdb/commit/f122f94291bfbc87496efca3c04540bb190b985a

https://github.com/apache/couchdb/blob/master/src/couch/src/couch_os_daemons.erl#L227

**Comment by wohali** [comment]
@nickva Right, I knew about f122f94. But with Windows nothing is trivial so I'd want to be extra sure ;)

**Comment by nickva** [comment]
@wohali indeed. Also this might be a case where R16B acts differently as the fix for it came in http://erlang.org/download/otp_src_17.0-rc1.readme (search for OTP-10842). Wonder if it is a case where on Windows we support a smaller subset of Erlang releases...

**Comment by wohali** [comment]
@nickva practically speaking, no one runs on Windows without using the binaries we build, and those are built with 18.3 right now (or newer).

**Pull request merged**
