### PR TITLE
Fix for a function_clause crash in couch_native_process

### PR DESCRIPTION
**Pull request by AlexanderKaraberov**
## Overview

In case when CouchDB has a native query server enabled and we call an Erlang `map` function for the first time (therefore there is no view index) `couch_mrview_updater:start_update` calls `run(State, [<<"map_doc">> , Doc])` from the `couch_native_process` and after this view index is built and data is read from it. Unfortunately when the same Erlang map function is used for changes feed with `_view` filter, `couch_native_process` crashes with:
```
{"error":"error","reason":"{{function_clause,\n     [{couch_native_process,ddoc,\n          [{evstate, ....
```
Changes feed with `_view` filter allows to use existing map function as the filter and it doesn’t query the view index files. Furthermore `seq_indexed` option doesn't work correctly in the mrview (more details in [this thread](https://github.com/apache/couchdb/issues/1142#issuecomment-378228093)) hence `fast_view` filter (which allows to use a dedicated `seq` and `keyseq` indexes) was disabled in the CouchDB 2. As a consequence changes feed with `_view` will always call `run(#evstate{ddocs=DDocs}=State, [<<"ddoc">>])` and this call will crash with the aforementioned error.
This crash is caused by a missing implementation of `ddoc` function for `<<"views">>` FunPath case, because for requests like `/_changes?style=all_docs&filter=_view&view=test/repl` the `FunPath` will be: `[<<"views">>,<<"repl">>,<<"map">>]`. For JS map functions this does work because in this case `couch_query_server` delegates map to an external `couch_js` OS process.
This fix effectively provides that missing `ddoc` clause and it is based on the `FilterFun` one but matches return values of the `erlang:put()` function (which is called from the native `Emit` function) and it also matches `ok` and `false` return values for the cases when docs were not emitted and Erlang view just returned either `ok` or a `false` atom. 

## Testing recommendations

Here is a simple shell script which makes curl requests in order to populate a test db with dummy docs and design docs containing Erlang and JS `map` functions:

```bash
#!/bin/sh

# creating the db
curl -u admin:admin1 -X PUT http://127.0.0.1:5983/db1

#insert ddoc with erlang view
curl -u admin:admin1 -H "Content-Type: application/json" -X PUT http://127.0.0.1:5983/db1/_design/test -d '{"_id":"_design/test","language":"erlang","options":{"include_deleted":true,"include_design":true},"views":{"repl":{"map":"fun({Doc}) ->\n    Repl = lists:keyfind(<<\"repl\">>, 1, Doc),\n    if\n         Repl =:= {<<\"repl\">>, <<\"unsafe\">>} ->\n              ok;\n         true ->\n              DocId = case lists:keyfind(<<\"_id\">>, 1, Doc) of\n                   {<<\"_id\">>, Id} -> Id;\n                   false -> undefined\n              end,\n              Emit(DocId, null)\n    end\nend."}}}'

#insert second ddoc with js view
curl -u admin:admin1 -H "Content-Type: application/json" -X PUT http://127.0.0.1:5983/db1/_design/testjs -d '{"_id":"_design/testjs", "language":"javascript","options":{"include_deleted":true,"include_design":true},"views":{"repl":{"map":"function (doc) {\n\tif (doc.repl !== \"unsafe\") emit(doc._id, null);\n}"}}}'

#populate with 50 repl safe docs
for IDX in {1..50}; do curl -u admin:admin1 -H "Content-Type: application/json" -X POST http://127.0.0.1:5983/db1 -d '{"index":"'$IDX'", "repl": "safe"}'; done

#populate with 10 repl unsafe docs
for IDX in {51..60}; do curl -u admin:admin1 -H "Content-Type: application/json" -X POST http://127.0.0.1:5983/db1 -d '{"index":"'$IDX'", "repl": "unsafe"}'; done

#populate with 10 random docs
for IDX in {61..70}; do curl -u admin:admin1 -H "Content-Type: application/json" -X POST http://127.0.0.1:5983/db1 -d '{"index":"'$IDX'", "data": "test"}'; done

```

In order to test just run changes feed for both JS map:
```
curl -u admin:admin1 'http://127.0.0.1:5983/db1/_changes?style=all_docs&filter=_view&view=testjs/repl'
```
and Erlang one `filter=_view&view=test/repl` and compare the output including the `"last_seq"` which ought to be the same.

### CODE REVIEW

**Comment by wohali** [comment]
paging @eiri for PR review please

**Comment by eiri** [comment]
@wohali @AlexanderKaraberov Just to let you know, I'll get to it later this week, suffering from a flu right now.

**Comment by eiri** [comment]
This is rather embarrassing, but I still can't find time to look into it.

@iilyak, @nickva - if one of you have free cycles, can you revew this, please?

**Comment by iilyak** [comment]
This PR needs tests. I do believe that following would be sufficient. I am going to test it tonight:
```
diff --git a/src/couch/test/couch_changes_tests.erl b/src/couch/test/couch_changes_tests.erl
index 673f2faad..f529eb312 100644
--- a/src/couch/test/couch_changes_tests.erl
+++ b/src/couch/test/couch_changes_tests.erl
@@ -153,7 +153,9 @@ filter_by_view() ->
             fun setup/0, fun teardown/1,
             [
                 fun should_filter_by_view/1,
-                fun should_filter_by_fast_view/1
+                fun should_filter_by_fast_view/1,
+                fun should_filter_by_erlang_view/1
+
             ]
         }
     }.
@@ -665,6 +667,39 @@ should_filter_by_user_ctx({DbName, _}) ->
             ?assertEqual(UpSeq, LastSeq)
         end).

+should_filter_by_erlang_view({DbName, _}) ->
+    ?_test(
+        begin
+            DDocId = <<"_design/app">>,
+            DDoc = couch_doc:from_json_obj({[
+                {<<"_id">>, DDocId},
+                {<<"language">>, <<"javascript">>},
+                {<<"views">>, {[
+                    {<<"valid">>, {[
+                        {<<"map">>, <<"fun({Doc}) ->"
+                            " case lists:keyfind(<<\"doc3\">>, 1, Doc) ->"
+                                " Emit(<<\"doc3\">>, null); "
+                                " _ -> ok"
+                            " end "
+                        "end.">>}
+                    ]}}
+                ]}}
+            ]}),
+            ChArgs = #changes_args{filter = "_view"},
+            Req = {json_req, {[{
+                <<"query">>, {[
+                    {<<"view">>, <<"app/valid">>}
+                ]}
+            }]}},
+            ok = update_ddoc(DbName, DDoc),
+            {Rows, LastSeq, UpSeq} = run_changes_query(DbName, ChArgs, Req),
+            ?assertEqual(1, length(Rows)),
+            [#row{seq = Seq, id = Id}] = Rows,
+            ?assertEqual(<<"doc3">>, Id),
+            ?assertEqual(6, Seq),
+            ?assertEqual(UpSeq, LastSeq)
+        end).
```

**Comment by iilyak** [comment]
@AlexanderKaraberov: I did test the change with the test above. It fails without your change and passes with it. Could you either add the test to your PR or write another one if you think of better ways to test it?

Thank you for your contribution.

**Comment by AlexanderKaraberov** [comment]
@iilyak 
Yes sure. Sorry, I forgot to write proper tests before actually submitting my PR. I will run your test suite, verify whether it covers all the use cases and will include it in the PR. Hopefully today or tomorrow.

**Comment by AlexanderKaraberov** [comment]
Hi @iilyak , I've checked the test you had added and it's completely fine. Thanks!
`should_filter_by_erlang_view` is exactly what's needed and I've included this test in the PR.

**Comment by AlexanderKaraberov** [comment]
@iilyak 
Excuse me for inconvenience, I've screwed up my fork. Will re-open this PR as a new one to avoid all the clutter if you don't mind.

**Comment by AlexanderKaraberov** [comment]
Reopened as https://github.com/apache/couchdb/pull/1401
Shame on me

**Pull request closed without merging**
