### PR TITLE
WIP: Fix erlang 21 eunit failures

### PR DESCRIPTION
**Pull request by davisp**
Only making this a PR so that travis will run it.

### CODE REVIEW

**Comment by janl** [comment]
@davisp what is WIP about this?

**Comment by wohali** [comment]
@davisp that PR landed, but see https://github.com/mochi/mochiweb/pull/201

**Comment by janl** [comment]
It looks like mochiweb now support 21, but they haven’t made a release yet. Are we comfortable tagging their master in one of our releases? (I’m not really).

Depending on how the other issues are going on the 2.3.0 milestone, this might mean we leave 21 support for 2.4.0 (which I’d be okay with).

**Comment by nickva** [comment]
There is an issue with the CI not passing with the 21 fixes:

https://travis-ci.org/mochi/mochiweb/builds/407452186?utm_source=github_status&utm_medium=notification

Haven't dug enough to discover the reason yet but it seems like the tuple_call flag wasn't propagated somehow to all the module. https://travis-ci.org/mochi/mochiweb/jobs/407452187#L522

**Comment by nickva** [comment]
https://github.com/mochi/mochiweb/pull/204 <- mochiweb Erlang 21 compatibility fix

**Comment by wohali** [comment]
@nickva That mochiweb fix has landed.

**Comment by nickva** [comment]
And we already depend on it:

https://github.com/apache/couchdb-mochiweb/releases/tag/CouchDB-v2.18.0-1

Closing this issue

**Pull request closed without merging**
