### PR TITLE
Update rebar for COUCHDB-2978

### PR DESCRIPTION
**Pull request by garrensmith**
Update rebar and couch for latest changes to chttpd and couch.

### CODE REVIEW

**Comment by rnewson** [comment]
+1

**Comment by kxepal** [comment]
+1, but I think commit message could be better:

```
Update couch and chttpd apps for COUCHDB-2978
```

Because I was thought that you'd updated rebar version instead (:

**Comment by garrensmith** [comment]
@kxepal good point. I'll update the message on merge. Waiting for tests to pass.

**Comment by garrensmith** [comment]
merged.

**Pull request merged**
