### PR TITLE
Fix smoosh get_priority/2 case clause

### PR DESCRIPTION
**Pull request by nickva**
Fixes the case when get_index/3 returns a `database_not_found` error.

### CODE REVIEW

**Comment by nickva** [comment]
Before:

```
smoosh_server:get_priority(foo, {<<"shards/80000000-ffffffff/db2.1666895357">>, <<"x">>}).
** exception error: no case clause matching {database_does_not_exist,
                                                [{mem3_shards,load_shards_from_db,"db2",
                                                     [{file,"src/mem3_shards.erl"},{line,430}]},
                                                 {mem3_shards,load_shards_from_disk,1,
                                                     [{file,"src/mem3_shards.erl"},{line,405}]},
                                                 {mem3_shards,load_shards_from_disk,2,
                                                     [{file,"src/mem3_shards.erl"},{line,434}]},
                                                 {mem3_shards,for_docid,3,
                                                     [{file,"src/mem3_shards.erl"},{line,100}]},
                                                 {fabric_doc_open,go,3,
                                                     [{file,"src/fabric_doc_open.erl"},{line,39}]},
                                                 {couch_index_server,'-get_index/3-fun-0-',2,
                                                     [{file,"src/couch_index_server.erl"},{line,74}]}]}
     in function  smoosh_server:get_priority/2 (src/smoosh_server.erl, line 348)
```

With the PR:

```
smoosh_server:get_priority(foo, {<<"shards/80000000-ffffffff/db2.1666895357">>, <<"x">>}).
0
```

**Review by jaydoane — APPROVED** [review]
LGTM, although ideally we'd add a simple test to cover that case

**Review by iilyak — APPROVED** [review]
+1

**Review by jaydoane — APPROVED** [review]
Very nice improvements!

**Review by rnewson — APPROVED** [review]

**Pull request merged**
