### PR TITLE
Bump fauxton to v1.2.3

### PR DESCRIPTION
**Pull request by willholley**
## Overview

Use [Fauxton v1.2.3](https://github.com/apache/couchdb-fauxton/releases/tag/v1.2.3).

## Checklist

- [ ] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by wohali** [comment]
@willholley Will you be able to assist with https://github.com/apache/couchdb-documentation/issues/493 as well?

**Comment by Antonio-Maranhao** [comment]
I updated the Fauxton `v1.2.3` tag, so you're good to go.
Also added Fauxton changes to the 3.0.0 release notes in https://github.com/apache/couchdb-documentation/pull/494

**Comment by wohali** [comment]
@willholley I'm going to merge this here and `3.0.x` and `3.x`, but do we need a Fauxton 1.2.4 before we release 3.0.1 and 3.1.0?

**Comment by willholley** [comment]
there are a few small fixes to Fauxton since 1.2.3; @Antonio-Maranhao what do you think?

**Comment by garrensmith** [comment]
I would us to fix https://github.com/apache/couchdb-fauxton/issues/1037#issuecomment-609685270 before we cut another release

**Pull request merged**
