### PR TITLE
Upgrade to latest Sphinx 5.1.1 and fix the top Edit on Github link

### PR DESCRIPTION
**Pull request by nickva**
"Edit on Github" link wasn't working and pointing to a non-existent "index" file. This was most likely because we override the index.html template, so the  source renderer doesn't know what to link it to. Instead opt to make the top level "Edit on Github" point the docs readme page. Individual doc pages will point to their respective source pages.

In addition, we were quite a bit behind on on the sphinx version 1.5 vs 5.1.1 this has caused quite a bit of headaches over the years as we had to pin jinja2, docutils and other libraries versions to avoid breaking things.

The main issue after the upgrade was that the http domain became a bit more strict. After vendoring it in, we had to make a few multipart http examples use plaintext. On the positive side, it found broken references in the admin guide, so those were fixed. Since we're using the latest 5.1.1 opt to just use a python3 venv with a short setup.sh script. That should make it easier for contributors to build docs locally.

### CODE REVIEW

**Comment by nickva** [comment]
The rendered example of this PR is at https://docs.couchdb.org/en/try-to-fix-docs-edit-link/

**Review by big-r81 — APPROVED** [review]
Excellent @nickva 👍🏼🫶

only a small question: could we add httpdomain from sphinxcontrib over pip to easier update this extension?

**Comment by nickva** [comment]
> only a small question: could we add httpdomain from sphinxcontrib over pip to easier update this extension?

good idea, @big-r81, I'll give that a try

**Comment by nickva** [comment]
@big-r81 great suggestion! httpcontrib now come from pip

**Pull request merged**
