### PR TITLE
Fix favicon caching on leap year

### PR DESCRIPTION
**Pull request by kxepal**
COUCHDB-2956

### CODE REVIEW

**Comment by rnewson** [comment]
I think that works but I wonder if this is better;

```
{Date0, _} = calendar:universal_time(),
Days0 = calendar:date_to_gregorian_days(Date0),
Days1 = Days0 + 365,
Date1 = calendar:gregorian_days_to_date(Days1)
```

For caching, saying we cache for 365 days (rather than 1 year) seems fine.  Or we could look at how we determine cookie expiration.

**Comment by kxepal** [comment]
Sounds better, especially if one day we decide to make cache time configurable. Thanks!

**Comment by kxepal** [comment]
PR updated.

**Comment by rnewson** [comment]
+1

**Pull request merged**
