### PR TITLE
More test improvements and stabilization

### PR DESCRIPTION
**Pull request by sebastianrothbucher**
I did put in some more work to get the tests more stable - esp. replication.js (use random-generated databases throughout), the users_db / show_functions / and some other tests are back also. 

For n=1, it seems to be pretty stable already (also on lower computing power), for n=3 there's still work left (so is for the replication_db... tests; however: the core tests would be there already)

we should certainly merge after the RC1, any feedback is welcome still (it makes lots of sense to rebase after #400 and #401 is in - in fact merging them should be done before as this PR depends on them)

BTW: I sat down and drafted a short blog post on my lessons learned so far - any feedback highly welcome: https://gist.github.com/sebastianrothbucher/5e30ebbd98c64330f61ce87a9b8a4d00

### CODE REVIEW

**Comment by janl** [comment]
After applying #400 and #401 to master (nice work!) and rebasing the new master on top of this locally, I get reproducible test fails in `rewrite_js` and `show_documents`, and intermittent failures in `view_sandboxing` (sometimes it passes, sometimes not.

These are the errors:

```
test/javascript/tests/rewrite_js.js                            
    Error: false
Trace back (most recent call first):
    
  52: test/javascript/test_setup.js
      T(false)
 305: test/javascript/tests/rewrite_js.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
```

```
test/javascript/tests/show_documents.js                        
    Error: retry_part is not defined
Trace back (most recent call first):
    
 400: test/javascript/tests/show_documents.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
```

```
test/javascript/tests/view_sandboxing.js                       
    Error: expected '1', got 'null'
Trace back (most recent call first):
    
  52: test/javascript/test_setup.js
      T(false,"expected '1', got 'null'",(void 0))
 321: test/javascript/couch_test_runner.js
      TEquals(1,(void 0))
 129: test/javascript/tests/view_sandboxing.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
```

**Comment by sebastianrothbucher** [comment]
@janl thx 4 checking; I did a rebase against master (see above) and that knocks off two errors right away. I did improve what went wrong for show_documents as well. You can re-try some time (and CU in 30mins or so ;-) )

**Comment by janl** [comment]
this is relevant: https://github.com/apache/couchdb-chttpd/pull/116

**Comment by sebastianrothbucher** [comment]
Done & pushed ;-) (I did checkout chttpd's 116, make and make javascript) successfully. Just created a full new user so we won't hit the cache 4 sure.

**Pull request merged**
