### PR TITLE
Spidermonkey version NIF

### PR DESCRIPTION
**Pull request by big-r81**
## Overview

Created an Erlang NIF to get the Spidermonkey version from the linked library.

### CODE REVIEW

**Comment by janl** [comment]
@nickva @rnewson do we want to use this?

**Comment by rnewson** [comment]
not sure I understand the need. couchdb is built against a specific version of spidermonkey, isn't it? can it change at runtime without breaking?

**Comment by nickva** [comment]
It's a neat patch as it shows the exact version of SM, and presumably might show if somehow the build was misconfigured (we thought we built it with SM 78 but actually built it with 96). But I don't know if it's worth having one extra NIFs in the system just for that. So I am more inclined not to have it.

**Comment by rnewson** [comment]
I'm inclined against for same reason. if it were in the same `./src/couch/priv/couch_js` pile of native code then maybe

**Comment by big-r81** [comment]
It's fine be me too, to not having an extra nif. Before this PR, I backported this logic into `./couchjs -V` to print this version information from the command line. See #4262 for more details.

**Pull request closed without merging**
