### PR TITLE
fix: re-enable _doc_id filter optimisation path

### PR DESCRIPTION
**Pull request by janl**
wip fix for #1737 just to see how CI likes this, initial comments welcome

### CODE REVIEW

**Comment by wohali** [comment]
Could use a test case so we don't regress on this again.

**Comment by janl** [comment]
@wohali you mean when we add another clustering later? ;D

This needs conceptual approval before moving on.

Should this approach be acceptable, I'd also re-enable the design doc filter optimisation  the same way.

**Comment by wohali** [comment]
@janl Elixir now tests against a cluster, so, yes, we have the infrastructure in place :)

**Comment by janl** [comment]
@wohali tried to make a joke, got foiled by a typo, nvm :/

**Comment by janl** [comment]
cleaned up and ready for review

**Comment by wohali** [comment]
Holding for 2.3.0 per @rnewson. Thanks Bob!

**Pull request merged**
