### PR TITLE
Update Makefile.win to Include locald confs and clean configs in devclean

### PR DESCRIPTION
**Pull request by jjrodrig**
## Overview

#2660 modifies the exlixir target with a new config option in the dev/run script
This PR updates Makefile.win with the same change

As a side effect of #2660 the test CouchDB config may change between test targets (elixir, javascript) but devclean target didn't clean the etc folder and the execution order can produce errors. 

Running `make elixir` and then `make javascript` fails

## Testing recommendations
Sorry,  I don't have a Windows machine to test this...

`make elixir` must work in Windows

The following sequence must work
```
 make elixir
 make javascript
```

## Checklist

- [ ] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by wohali** [comment]
Hi @jjrodrig ,

In the future, now that you're a committer, feel free to work directly on a branch here in the `apache/couchdb` repo. That way, I don't have to pull from your fork (and you don't have to maintain one!) for these changes.

That said, I can't get `make elixir` to work. Note that it worked perfectly from a 3.0.0 checkout.

From a fresh checkout of your branch, `make elixir` fails. The `dev\run` script starts CouchDB which immediately crashes with:

```
kernel-poll not supported; "K" parameter ignored
{"init terminating in do_boot",{{error,{"no such file or directory","setup.app"}},[{boot_node,start_app,3,[{file,"c:/relax/couchdb-git/dev/boot_node.erl"},{line,146}]},{lists,foldl,3,[{file,"c:/relax/otp/lib/stdlib/src/lists.erl"},{line,1263}]},{init,start_em,1,[{file,"init.erl"},{line,1085}]},{init,do_boot,3,[{file,"init.erl"},{line,793}]}]}}
init terminating in do_boot ({{error,{no such file or directory,setup.app}},[{boot_node,start_app,3,[{_},{_}]},{lists,foldl,3,[{_},{_}]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
```

I tried changing the direction of the slashes in the added `--locald-config` line to no effect.

:thinking:

**Comment by jjrodrig** [comment]
Hi @wohali 
I've the same error when I don't have a successful `make couch' before to run 'make elixir'
The 'make couch' was successful?

I managed to execute `dev\run` (without building couchdb) in a windows and I've test that the local.d folder is created and the test-config.ini is placed on the folder.  

I've tested / and \ path separators and both are working.

**Comment by wohali** [comment]
So it appears that running

```
make elixir
make javascript
```

works but

```
make elixir javascript
```

does not. This is *also* a failure on Unix, though, so I'm not going to block this PR.

Most importantly, `make check` works when run twice in a row.

If you can sort out why `make elixir javascript` fails and open a new PR with a fix (in both Makefiles), that'd be great. (Honestly, I'd like to fix `make check` so it's not shelling out to a new `make` process 5 times in a row...that's bad code smell that we've cargo culted for years now. :wink:)

**Comment by jjrodrig** [comment]
Thanks! @wohali 

The issue that appears when you run multiple targets in a make execution is that the `dev/run` environment is not properly cleaned. 

>  make -n elixir javascript 
Produces the following executions
```
mix local.rebar --force && mix local.hex --force && mix deps.get
mix format --check-formatted
mix credo
rm -rf dev/lib/*/data
rm -rf dev/lib/*/etc
dev/run ""-c 'startup_jitter=0' -c 'default_security=admin_local'"" -a adm:pass -n 1 \
		--enable-erlang-views \
		--locald-config test/elixir/test/config/test-config.ini \
		--no-eval 'mix test --trace --exclude without_quorum_test --exclude with_quorum_test '
mkdir -p share/www/script/test
mkdir -p src/fauxton/dist/release/test
cp test/javascript/tests/lorem*.txt src/fauxton/dist/release/test/
dev/run -n 1 -q --with-admin-party-please \
            --enable-erlang-views \
            ""-c 'startup_jitter=0' -c 'default_security=admin_local'"" \
            'test/javascript/run --suites "" \
            --ignore ""'

```
The 'devclean' target is
```
rm -rf dev/lib/*/data
rm -rf dev/lib/*/etc
```
Which is executed only at the beginning of the execution and not between the elixir and javascript targets.

It is a minor tweak to allow to run 'javascript' target with other test targets in the same 'make' execution. I can add it to this PR.

**Comment by jjrodrig** [comment]
Hi @wohali, now elixir and javascript can be chained. It is ok for you?

Thanks!

**Comment by wohali** [comment]
Weird, I still don't understand why having to subshell to Make works. This needs further study.

Go ahead and merge, I'll open a new ticket.

**Pull request merged**
