### PR TITLE
Extract helper to execute a function in a new process

### PR DESCRIPTION
**Pull request by willholley**
## Overview

Adds a helper that executes a function in a new process, with standardized error handling and logging.

## Testing recommendations

The test suite should exercise the code paths that have changed (currently document update and _find).

## Related Issues or Pull Requests

n/a

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by eiri** [comment]
I don't think this helper belongs to fabric, it's pretty generic, so I'd say it fits better in [couch_util](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_util.erl).

As a matter a fact a quite similar `couch_util:with_proc/4` function is already there, so it might be better to fuse them together, given that `defer` here is missing explicit timeout handeling.

**Comment by willholley** [comment]
thanks @eiri - good thought. I wasn't aware of `couch_util:with_proc/4` so I'll have a look at whether that can be used instead.

**Comment by willholley** [comment]
huh - I can't find any uses of `couch_util:with_proc/4` - is it redundant?

**Comment by eiri** [comment]
@willholley Used in [cassim](https://github.com/apache/couchdb-cassim/blob/master/src/cassim_metadata_cache.erl#L200) evidently. But can't disagree, it's not widly known, I discovered it only because I thought your helper better fits into couch_util and went to scan code there :)

**Comment by janl** [comment]
Closing until progress.

**Pull request closed without merging**
