### PR TITLE
Whait db close a little bit before failing test

### PR DESCRIPTION
**Pull request by iilyak**
## Overview

Databases are closed asynchronously. However it was not accounted for in
the test case. This commit waits database to close before it makes a
decision to abort the test. It uses default timeout of 5 sec.
I.e. if test case detects that database is still opened after 5 sec
it considers it as failure.

## Testing recommendations

make eunit apps=couch_index tests=compaction_test
## Checklist

- [ ] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by eiri** [comment]
Looks good to me, didn't know we have `test_util:wait/1,2,3` function. Except maybe pass timeout explicitly? " 'wait' for how long?" was my first question when I've seen the change.

**Comment by iilyak** [comment]
@eiri: What timeout value would you recommend? I am considering 500.

**Comment by eiri** [comment]
@iilyak hard to guess, to be honest, 500 or 1000 both looks good to me. test_util's `wait` default is 5000, but it's more fitting for the tests around os_process related modules, it's common default there.

**Comment by iilyak** [comment]
@wohali: Sorry for the delay.

**Comment by wohali** [comment]
@iilyak Hey I'm just glad people are starting to help ;)

**Pull request merged**
