### PR TITLE
doc: explain new workflow for developing

### PR DESCRIPTION
**Pull request by robertkowalski**
@rnewson does this makes sense?

// cc: @michellephung

### CODE REVIEW

**Comment by davisp** [comment]
You can add that ./dev/run -n 1 will spin up a single node as well. Obviously that's just a single node running the full clustered interface. If anyone feels like making a special --single-node flag and the appropriate changes to ./dev/run and dev/boot_node.erl that'd be something we could think about as well.

Until then I don't think adding these instructions would be detrimental to single node development.

**Comment by davisp** [comment]
Erm, so +1 to merging this.

**Comment by kxepal** [comment]
I think better to add --single-node flag, because one thing is running a cluster with single node and completely the other is running a single node without cluster setup at all.

I'll take a look on what could be done for this. But related this PR +1 for merge.

**Comment by robertkowalski** [comment]
merged as d881dcf5ac990c44d00b2cd49c0e4ff67ae861c5

**Pull request closed without merging**
