### PR TITLE
Remove installation via snap package

### PR DESCRIPTION
**Pull request by big-r81**
Currently there is no maintainer of the snap package. 
Removing the docs until new maintainer is found.

Closes https://github.com/apache/couchdb-pkg/issues/114.

### CODE REVIEW

**Review by nickva — APPROVED** [review]
+1

**Comment by sblaisot** [comment]
What a shame.

No snap package maintainer, no Debian 12 package more than 4 monthes after release. Is couchdb still alive?

**Comment by big-r81** [comment]
@sblaisot I'm happy to see your contributions to the snap package in the next days...

**Comment by sblaisot** [comment]
@big-r81 No sooner said than done. Not for snap package but at least for deb12 packages. This was a 15 minutes job. it is completely ueless because I have no mean to test it without visibility on CI and repos.

- https://github.com/apache/couchdb-ci/pull/59
- https://github.com/apache/couchdb-pkg/pull/116

Of course, as I have no mean to test it and no visibility on CI and repos, it must still be addressed by some core team member

**Comment by big-r81** [comment]
> @big-r81 No sooner said than done. Not for snap package but at least for deb12 packages. This was a 15 minutes job. it is completely useless because I have no mean to test it without visibility on CI and repos.
> 
>     * [Handle Debian 12 Bookworm couchdb-ci#59](https://github.com/apache/couchdb-ci/pull/59)
> 
>     * [Handle Debian 12 Bookworm couchdb-pkg#116](https://github.com/apache/couchdb-pkg/pull/116)
> 
> 
> Of course, as I have no mean to test it and no visibility on CI and repos, it must still be addressed by some core team member

@sblaisot Thank you for your contribution. Maybe with a nicer attitude for the [next](https://github.com/apache/couchdb/pull/4826#issuecomment-1786063439) time. ;-)
In the meantime someone (😋) else had the same idea.

- https://github.com/apache/couchdb-ci/pull/58
- https://github.com/apache/couchdb-pkg/pull/115

We're in preparation of a new CouchDB release and want to update our CI packages before. At the moment we are waiting for an Erlang patch to land in OTP/25+ which we want to get integrated first. I take a quicklook of your PRs and lets merge the best from both. I'll get back to you on this.

**Comment by nickva** [comment]
Debian Bookworm packages for x86_64 should be available via the standard installation method https://docs.couchdb.org/en/stable/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

Docs still don't mention it, we should update that as well, if @big-r81 doesn't get to it before I do, I'll do tomorrow.

There is a PR to add snap packages back in: https://github.com/apache/couchdb-pkg/pull/119. Though none of us know very much about snaps so that may take a while.

**Comment by big-r81** [comment]
@nickva Hi created a #4840 for Debian 12, but I wouldn't backport it to the `stable` docs branch (we didn't it consequently for all 3.3.x docs PRs). While we are in progress of releasing a new version, `latest` would become `stable` and then it would be mentioned there.

**Pull request merged**
