### PR TITLE
Fix _approx_count_distinct on non-clustered interface, optimize _stats

### PR DESCRIPTION
**Pull request by kocolosk**
## Overview

One bugfix and one enhancement here. The bugfix is that the `finalize` operation introduced for `_approx_count_distinct` was not being executed on view requests coming in through the non-clustered interface, so any attempt to use that reduce function there would crash.

The enhancement is to take advantage of that `finalize` operation to optimize the builtin `_stats` reduce function. Previously the reduce function would always write down an ejson form for the 5 statistical quantities to disk as it could never know whether the `rereduce` function was being called during indexing or during querying. Now that we have the `finalize` operation (which only runs at query time) we can store a more compact format on disk and avoid continuously translating back and forth between the compact and ejson formats during indexing. This should result in slightly more efficient builds and slightly smaller resulting indexes.

## Testing recommendations

Run the _stats tests against clustered and non-clustered interfaces.

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [x] Documentation reflects the changes;

### CODE REVIEW

**Comment by kocolosk** [comment]
OK I think that's sorted now. Tested both `_stats` and `_approx_count_distinct` on both 5984 and 5986. Not the most elegant thing in the world but I think it's clear enough and won't be too brittle going forward if we should need to do other things around finalizing these reductions.

**Comment by wohali** [comment]
dare I ask for automated tests?

**Comment by kocolosk** [comment]
@wohali not 100% sure what you mean. Travis is running the automated tests for both of those and catching where I've missed something. In this case I missed the fact that `_statsorama` and `_stats\nare\nawesome` are apparently valid ways to invoke the `_stats` reduce function 🙄. Thanks JChris!

If you're saying I ought to run the full test suite locally before opening the PR ... yes OK I need to figure out how to do that. I futzed with the firewall on my laptop a bit and eventually gave up.

If you're saying we need to test both 5984 and 5986 as part of the test suite that's probably worth filing an issue.

**Comment by wohali** [comment]
My mistake - I thought this was a new feature (missed that that particular PR already landed) and was looking for tests specific for those new features. If the tests are already in place, no need to add any.

Yeah, that sounds like a useless feature we should remove.

`make check` should run the full test suite for you, at least on a single Erlang. No need to test against all the various erlangs, Travis can take care of that. Not sure what's up with your laptop if `make check` fails there.

**Comment by kocolosk** [comment]
Ah yeah @nickva added JS tests to my original PR for the feature.

When I run `make check` locally it hangs because 3 dialogs pop up asking me to allow incoming network access for the various `beam.smp` processes and then they disappear before I can address them. 🤷‍♂️ I'm sure I'll sort it out eventually.

**Comment by wohali** [comment]
Ah, Little Snitch? Try adding blanket allow rules for it. The new Silent Mode stacks up the notifications so you can review them later, that might work for you.

https://help.obdev.at/littlesnitch/#/intro-opmodes

**Comment by nickva** [comment]
One more thing that needs to be done is to include the app in the app dependencies for couch:

https://github.com/apache/couchdb/blob/master/src/couch/src/couch.app.src#L50

**Comment by nickva** [comment]
PR to add hyper to app dependencies: https://github.com/apache/couchdb/pull/1379

**Pull request merged**
