### PR TITLE
implement this same as maybe_boot_clouseau

### PR DESCRIPTION
**Pull request by rnewson**
refinement of https://github.com/apache/couchdb/pull/4957 to match maybe_boot_clouseau.

### CODE REVIEW

**Comment by rnewson** [comment]
I'm also questioning whether 4957 did anything as I already had a check for this at the top of boot_nouveau:

```
def boot_nouveau(ctx):
    if not ctx["with_nouveau"]:
        return
```

testing locally `./dev/lib/nouveau.yaml` is not created when doing `dev/run` unless you also add `--with-nouveau`

**Comment by jiahuili430** [comment]
> I'm also questioning whether 4957 did anything as I already had a check for this at the top of boot_nouveau:
> 
> ```
> def boot_nouveau(ctx):
>     if not ctx["with_nouveau"]:
>         return
> ```
> 
> testing locally `./dev/lib/nouveau.yaml` is not created when doing `dev/run` unless you also add `--with-nouveau`

If `nouveau.yaml` does not exist in the `rel` directory, then `generate_nouveau_config(ctx)` will get `FileNotFoundError`.
So, I added an if statement to check whether the `nouveau' was enabled.

**Review by jiahuili430 — APPROVED** [review]

**Comment by rnewson** [comment]
I think your testing was based on the PR during its development. The merged version had the

```
if not ctx["with_nouveau"]:
        return
```

check in it. As such I think the work in #4957 didn't do anything for the merged version of this work?

Anyway, it makes sense to match the clouseau approach anyway.

**Review by nickva — COMMENTED** [review]
+1

**Comment by nickva** [comment]
Hmm, it would be nice to default to `--with-nouveau` if we already configured nouveau. I'll see if we can read the install.mk and pick up the dev/run defaults from there perhaps?

**Comment by rnewson** [comment]
enh, just you ./configure'd with --enable-nouveau doesn't mean you always want to launch it with dev/run, but I guess as a default it makes sense. I'm just used to setting both each time that it doesn't bother me. see how we handle haproxy also

**Comment by nickva** [comment]
I tried it here https://github.com/apache/couchdb/pull/4961, but needed also a way to explicitly disable nouveau during some tests which didn't expect it (mango, etc), so it would need an extra `--without-nouveau` argument, and that was getting a bit too clunky.

**Pull request merged**
