### PR TITLE
update Fauxton and Docs git repo urls

### PR DESCRIPTION
**Pull request by garrensmith**
Update Git repos

## Overview

Fauxton and Documentation are now using gitbox. This means we need to change the repository urls to use github.

## Testing recommendations

`./configure` should now run

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [x] Documentation reflects the changes;
- [x] I will not forget to update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script)
      with the correct commit hash once this PR get merged.

### CODE REVIEW

**Comment by lostnet** [comment]
My automated builds are using anonymous clone over https, so git over ssh fails on the github hostkey, etc. Maybe https urls would work correctly for both configurations: 

```
-{docs,             "documentation",    "59a887a97f9b6befc6de0c5bdaf17d79fb7f915d", [raw]},
+{docs,             {url, "https://github.com/apache/couchdb-documentation.git"},    "59a887a97f9b6befc6de0c5bdaf17d79fb7f915d", [raw]},
 {ddoc_cache,       "ddoc-cache",       "c762e90a33ce3cda19ef142dd1120f1087ecd876"},
 {ets_lru,          "ets-lru",          "c05488c8b1d7ec1c3554a828e0c9bf2888932ed6"},
 {fabric,           "fabric",           "d22903c0ceaf19a305e67b5b7322cbdc4e5e9340"},
-{fauxton,          "fauxton",          {tag, "v1.1.9"}, [raw]},
+{fauxton,          {url, "https://github.com/apache/couchdb-fauxton.git"},          {tag, "v1.1.9"}, [raw]},
```

**Comment by wohali** [comment]
I'm confused. Are the canonical URLs for our repos now at github.com or gitbox.apache.org? I thought it was the latter, which would make this PR incorrect.

**Comment by kxepal** [comment]
I'm with @wohali.

**Comment by garrensmith** [comment]
It's both, but it seems the preferred way is to use the github repo's and use gitbox as a fallback 

All misspelling thanks to my iPhone.




On Thu, Mar 9, 2017 at 8:49 PM +0200, "Alexander Shorin" <notifications@github.com> wrote:












I'm with @wohali.

**Comment by janl** [comment]
> It's both, but it seems the preferred way is to use the github repo's and use gitbox as a fallback 

There is no preferred way. Individual developers can pick either route.

As for where the canonical source for CouchDB lives, it is clearly gitbox.

**Comment by garrensmith** [comment]
I'm closing this. @nickva did a much better fix and its in master

**Pull request closed without merging**
