### PR TITLE
Test users db security rules on clustered interface

### PR DESCRIPTION
**Pull request by mikewallace1979**
Explicitly test authentication_db security rules when authentication_db is on the clustered interface (5984).

COUCHDB-2452

### CODE REVIEW

**Comment by davisp** [comment]
LGTM

**Comment by kxepal** [comment]
Related:
https://github.com/apache/couchdb-chttpd/pull/12
https://github.com/apache/couchdb-couch/pull/20
https://github.com/apache/couchdb-couch-mrview/pull/11

**Comment by kxepal** [comment]
Hey @sagelywizard ! Sorry for long time waiting. Could you rebase your PR (and related as well) here, please?

**Comment by mikewallace1979** [comment]
Oof this was a truly unpleasant piece of work :)

I'll give it a shot and see what fun issues I run into.

**Comment by kxepal** [comment]
@mikewallace1979 yea, sorry for that /:

**Pull request closed without merging**
