### PR TITLE
Ensure chttpd pids have a proper random seed

### PR DESCRIPTION
**Pull request by chewbranca**
## Overview

Currently chttpd pids are not properly seeded for random number generation. This ensures that they are.

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by nickva** [comment]
+1

**Comment by davisp** [comment]
Don't you need an /integer specification on those?

**Comment by davisp** [comment]
Also might make sense to pull it out into a function.

**Comment by nickva** [comment]
Integer is the default, I think

**Comment by davisp** [comment]
Huh. I would've expected binary as the default but I guess I just add specifiers out of habit.

**Comment by chewbranca** [comment]
Yeah I'm thinking we would be better served by a function like:

```erlang
maybe_seed() ->
    case get(random_seed) of
        undefined ->
            <<A:32, B:32, C:32>> = crypto:rand_bytes(12),
            Seed = {A, B, C},
            random:seed(Seed),
            Seed;
        Seed ->
            Seed
end.
```

**Comment by chewbranca** [comment]
It's a shame we can't use the `rand` module, as `rand` takes care of this automatically, but it's not in all the versions of Erlang we support. The `random` module has a terrible default seed: https://github.com/erlang/otp/blob/master/lib/stdlib/src/random.erl#L44-L45

**Comment by nickva** [comment]
@chewbranca why terrible? It's a perfectly fine randomly chosen number :P 

https://www.xkcd.com/221/

**Comment by nickva** [comment]
@davisp agree. Binary would seem to be a default type for a ... binary. Not sure why integers were picked.

**Comment by chewbranca** [comment]
@nickva well if `{3172, 9814, 20125}.` was chosen by way of random dice roll then we should be good. I feel bad for whoever had to roll dice that many times, although perhaps they had help from Emanuel Czuber.

**Comment by chewbranca** [comment]
Closing this out.

**Pull request closed without merging**
