### PR TITLE
Release 3.3.2 version bump

### PR DESCRIPTION
**Pull request by nickva**
We're forward porting 3.3.2 version bump commit to main

### CODE REVIEW

**Review by rnewson — APPROVED** [review]
noting that this means main branch is _at least as new_ as the last release, 3.3.2. but main definitely is _not_ the same code as the 3.3.2 release.

**Comment by big-r81** [comment]
Isn’t 3.3.2 a sub-set of main?

**Comment by nickva** [comment]
Closing in favor of https://github.com/apache/couchdb/pull/4593

**Comment by nickva** [comment]
@big-r81 you're right, normally we go from main -> 3.3.x but some changes we haven't been making to main and only made them to 3.3.2, some whatnew release notes and the version bump at least so this just bring those into main, so we should try to keep them in sync if possible (at least version-wise main is certainly closer to 3.3.2 in features than 3.3.1).

**Pull request closed without merging**
