### PR TITLE
mango: fix $beginsWith range

### PR DESCRIPTION
**Pull request by nickva**
This is a full jenkin runs for the `mango-begingswith-fixes` pr

### CODE REVIEW

**Comment by pgj** [comment]
Why is not #4829 enough?

**Comment by nickva** [comment]
> Why is not #4829 enough?

noticed some failures there and was wondering if it just need to be rebased

**Comment by pgj** [comment]
Okay.

**Comment by nickva** [comment]
the build passed! closing the pr

**Pull request closed without merging**
