### PR TITLE
Remove js harness & tests

### PR DESCRIPTION
**Pull request by wohali**
## Overview

This PR removes the JavaScript test suite, the test harness, and all support for the test harness and its options in `couchjs`.

It further removes references to `libcurl` from the build process and install documentation, as CouchDB no longer depends on it. In the process I also noticed we no longer require `help2man`, so that is also removed from the INSTALL readme.

## Testing recommendations

`make check` should pass on all platforms.

## Related Issues or Pull Requests

Possible because of #3192 and all the great work by @jjrodrig , @dottorblaster and many others for converting the suite to Elixir. Great work!

## Checklist

- [X] Code is written and works correctly
- [X] Changes are covered by tests
- [X] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`

### CODE REVIEW

**Review by davisp — APPROVED** [review]
+1 Bye bye, JS tests!

**Comment by dottorblaster** [comment]
Wow. This is an amazing milestone, congratulations to us all! ❤️

**Review by jjrodrig — APPROVED** [review]
It is ok for me. 
I think that we can remove some Makefile targets but we can do it in a separate PR
I didn't imagine this impact! Congrats to all!

**Review by dottorblaster — APPROVED** [review]

**Comment by wohali** [comment]
@jjrodrig OK, removed those targets too.

**Pull request merged**
