### PR TITLE
Handle `not_found` lookups removing ddoc cache key

### PR DESCRIPTION
**Pull request by jaydoane**
## Overview

Current implementation of `ddoc_cache_lru:remove_key/2` assumes that
lookups always return values, but these log entries beg to differ:

```
[error] 2021-12-10T02:25:21.622743Z node1@127.0.0.1 <0.18923.9> -------- gen_server ddoc_cache_lru terminated with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:308) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:637) <= gen_server:handle_msg/6(line:711) <= proc_lib:init_p_do_apply/3(line:249)

[error] 2021-12-10T02:25:21.623418Z node1@127.0.0.1 <0.18923.9> -------- CRASH REPORT Process ddoc_cache_lru (<0.18923.9>) with 0 neighbors crashed with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:308) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:637) <= gen_server:handle_msg/6(line:711) <= proc_lib:init_p_do_apply/3(line:249); initial_call: {ddoc_cache_lru,init,['Argument__1']}, ancestors: [ddoc_cache_sup,<0.4537.0>], message_queue_len: 2, links: [<0.4541.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 545194

[error] 2021-12-10T02:25:21.623898Z node1@127.0.0.1 <0.4541.0> -------- Supervisor ddoc_cache_sup had child ddoc_cache_lru started with ddoc_cache_lru:start_link() at <0.18923.9> exit with reason no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:308) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:637) <= gen_server:handle_msg/6(line:711) <= proc_lib:init_p_do_apply/3(line:249) in context child_terminated
```

This checks the return values of `khash:lookup` and only proceeds to
delete keys if the results are other than `not_found`.

## Testing recommendations

```
make check
```

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by nickva** [comment]
It would be interesting to see how it could plausibly get into that state. It looks like the entry process exited `normal` and we handled it in `handle_info` at `ddoc_cache_lru:handle_info/2(line:219)`. We [found](https://github.com/apache/couchdb/blob/3.x/src/ddoc_cache/src/ddoc_cache_lru.erl#L215) the Pid in the `Pids` table but the key, which we assumed would be present wasn't there.

It could be a race condition somehow or multiple entries (Pids) point to the same key?

**Comment by jaydoane** [comment]
Looks like [someone else found this alarming](https://github.com/apache/couchdb/discussions/3919) too.

**Comment by nickva** [comment]
It looks like @eiri may have found the reason for this in https://github.com/apache/couchdb/issues/1349#issuecomment-481279977 from a while back

**Comment by jaydoane** [comment]
> It would be interesting to see how it could plausibly get into that state. It looks like the entry process exited `normal` and we handled it in `handle_info` at `ddoc_cache_lru:handle_info/2(line:219)`. We [found](https://github.com/apache/couchdb/blob/3.x/src/ddoc_cache/src/ddoc_cache_lru.erl#L215) the Pid in the `Pids` table but the key, which we assumed would be present wasn't there.
> 
> It could be a race condition somehow or multiple entries (Pids) point to the same key?

I had this happen again recently on my dev environment:
```
[error] 2022-03-27T01:25:26.061197Z node1@127.0.0.1 <0.4240.120> -------- gen_server ddoc_cache_lru terminated with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:299) <= ddoc_cache_lru:handle_info/2(line:217) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226)
  last msg: redacted
     state: {st,#Ref<0.3817933327.115212289.259708>,#Ref<0.3817933327.115212289.259709>,<0.4822.120>}
    extra: []
[error] 2022-03-27T01:25:26.061348Z node1@127.0.0.1 <0.4240.120> -------- gen_server ddoc_cache_lru terminated with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:299) <= ddoc_cache_lru:handle_info/2(line:217) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226)
  last msg: redacted
     state: {st,#Ref<0.3817933327.115212289.259708>,#Ref<0.3817933327.115212289.259709>,<0.4822.120>}
    extra: []
[error] 2022-03-27T01:25:26.061483Z node1@127.0.0.1 <0.4240.120> -------- CRASH REPORT Process ddoc_cache_lru (<0.4240.120>) with 0 neighbors crashed with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:299) <= ddoc_cache_lru:handle_info/2(line:217) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226); initial_call: {ddoc_cache_lru,init,['Argument__1']}, ancestors: [ddoc_cache_sup,<0.4627.0>], message_queue_len: 0, links: [<0.4822.120>,<0.4631.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 29, reductions: 2103851
[error] 2022-03-27T01:25:26.061611Z node1@127.0.0.1 <0.4240.120> -------- CRASH REPORT Process ddoc_cache_lru (<0.4240.120>) with 0 neighbors crashed with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:299) <= ddoc_cache_lru:handle_info/2(line:217) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226); initial_call: {ddoc_cache_lru,init,['Argument__1']}, ancestors: [ddoc_cache_sup,<0.4627.0>], message_queue_len: 0, links: [<0.4822.120>,<0.4631.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 29, reductions: 2103851
[error] 2022-03-27T01:25:26.061743Z node1@127.0.0.1 <0.4631.0> -------- Supervisor ddoc_cache_sup had child ddoc_cache_lru started with ddoc_cache_lru:start_link() at <0.4240.120> exit with reason no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:299) <= ddoc_cache_lru:handle_info/2(line:217) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226) in context child_terminated
[error] 2022-03-27T01:25:26.061829Z node1@127.0.0.1 <0.4631.0> -------- Supervisor ddoc_cache_sup had child ddoc_cache_lru started with ddoc_cache_lru:start_link() at <0.4240.120> exit with reason no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:299) <= ddoc_cache_lru:handle_info/2(line:217) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226) in context child_terminated
```
which was puzzling because I didn't think there was _anything_ using ddocs in that environment. So I patched `ddoc_cache_lru` with the following:
```diff
--- a/src/ddoc_cache/src/ddoc_cache_lru.erl
+++ b/src/ddoc_cache/src/ddoc_cache_lru.erl
@@ -124,6 +124,8 @@ handle_call({start, Key, Default}, _From, St) ->
                     true = ets:update_element(?CACHE, Key, {#entry.pid, Pid}),
                     ok = khash:put(Pids, Pid, Key),
                     store_key(Dbs, Key, Pid),
+                    couch_log:info("~p:start Key=~p Pid=~p, Pids=~p Dbs=~p",
+                        [?MODULE, Key, Pid, Pids, Dbs]),
                     {reply, {ok, Pid}, St};
                 full ->
                     ?EVENT(full, Key),
```
and these showed in my logs at a rate of one per second.
```erlang
[info] 2022-03-27T22:41:11.994176Z node1@127.0.0.1 <0.4636.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.26100.17>, Pids=#Ref<0.3262557261.2829713410.69203> Dbs=#Ref<0.3262557261.2829713410.69204>
[info] 2022-03-27T22:41:12.994058Z node1@127.0.0.1 <0.4636.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.26085.17>, Pids=#Ref<0.3262557261.2829713410.69203> Dbs=#Ref<0.3262557261.2829713410.69204>
[info] 2022-03-27T22:41:13.994136Z node1@127.0.0.1 <0.4636.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.26173.17>, Pids=#Ref<0.3262557261.2829713410.69203> Dbs=#Ref<0.3262557261.2829713410.69204>
[info] 2022-03-27T22:41:14.994415Z node1@127.0.0.1 <0.4636.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.26190.17>, Pids=#Ref<0.3262557261.2829713410.69203> Dbs=#Ref<0.3262557261.2829713410.69204>
[info] 2022-03-27T22:41:15.994461Z node1@127.0.0.1 <0.4636.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.26157.17>, Pids=#Ref<0.3262557261.2829713410.69203> Dbs=#Ref<0.3262557261.2829713410.69204>
[info] 2022-03-27T22:41:16.994359Z node1@127.0.0.1 <0.4636.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.26269.17>, Pids=#Ref<0.3262557261.2829713410.69203> Dbs=#Ref<0.3262557261.2829713410.69204>
```
So it looks like your second guess that

> multiple entries (Pids) point to the same key

is correct, since these apparently all have the same key (of a non-existent ddoc), but are different PIDs.

**Comment by nickva** [comment]
@jaydoane interesting find. I stared some more at the code and still couldn't figure how we could end up with a not_found in https://github.com/apache/couchdb/blob/f801d400bd880644e74098070da82b5703ff0477/src/ddoc_cache/src/ddoc_cache_lru.erl#L299

The update to the Pids and Dbs khashes happen only in the ddoc_cache_lru `gen_server` https://github.com/apache/couchdb/blob/3.x/src/ddoc_cache/src/ddoc_cache_lru.erl#L122-L126 so I couldn't come up with a sequence of events to end up with them out of sync.

**Comment by jaydoane** [comment]
I added logging to `ddoc_cache_entry:terminate/1` as well:
```
[info] 2022-03-29T02:54:26.712593Z node1@127.0.0.1 <0.4621.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.25927.8>, Pids=#Ref<0.4244486069.2869821445.124970> Dbs=#Ref<0.4244486069.2869821445.124971>
[info] 2022-03-29T02:54:26.713215Z node1@127.0.0.1 <0.25927.8> -------- ddoc_cache_entry:terminate St={st,{ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}},{open_ok,{not_found,missing}},undefined,undefined,undefined,1}
[info] 2022-03-29T02:54:27.148635Z node1@127.0.0.1 <0.4621.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.25936.8>, Pids=#Ref<0.4244486069.2869821445.124970> Dbs=#Ref<0.4244486069.2869821445.124971>
[info] 2022-03-29T02:54:27.149547Z node1@127.0.0.1 <0.25936.8> -------- ddoc_cache_entry:terminate St={st,{ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}},{open_ok,{not_found,missing}},undefined,undefined,undefined,1}
[info] 2022-03-29T02:54:27.712771Z node1@127.0.0.1 <0.4621.0> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.26015.8>, Pids=#Ref<0.4244486069.2869821445.124970> Dbs=#Ref<0.4244486069.2869821445.124971>
[info] 2022-03-29T02:54:27.713406Z node1@127.0.0.1 <0.26015.8> -------- ddoc_cache_entry:terminate St={st,{ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}},{open_ok,{not_found,missing}},undefined,undefined,undefined,1}
```
and noticed that there's typically ~1ms between spawn and termination of a ddoc_cache_entry.

If I artificially widen that gap by adding a delay in terminate like so:
```diff
--- a/src/ddoc_cache/src/ddoc_cache_entry.erl
+++ b/src/ddoc_cache/src/ddoc_cache_entry.erl
@@ -145,6 +145,8 @@ init({Key, Wrapped}) ->
     gen_server:enter_loop(?MODULE, [], St, hibernate).
 
 terminate(_Reason, St) ->
+    timer:sleep(1),
+    couch_log:info("~p:terminate St=~p", [?MODULE, St]),
     #st{
         key = Key,
         opener = Pid,
```

I can reproduce this every time using this in a remsh:
```
(node1@127.0.0.1)8> ddoc_cache:open(<<"users">>, <<"_design/feature_flags">>), ddoc_cache:open(<<"users">>, <<"_design/feature_flags">>).
{not_found,missing}
```
which does this in the logs:
```
[info] 2022-03-29T04:06:01.698265Z node1@127.0.0.1 <0.14792.12> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.18310.12>, Pids=#Ref<0.4244486069.2877947905.247295> Dbs=#Ref<0.4244486069.2877947905.247296>
[info] 2022-03-29T04:06:01.700248Z node1@127.0.0.1 <0.14792.12> -------- ddoc_cache_lru:start Key={ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}} Pid=<0.18373.12>, Pids=#Ref<0.4244486069.2877947905.247295> Dbs=#Ref<0.4244486069.2877947905.247296>
[info] 2022-03-29T04:06:01.701389Z node1@127.0.0.1 <0.18310.12> -------- ddoc_cache_entry:terminate St={st,{ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}},{open_ok,{not_found,missing}},undefined,undefined,undefined,1}
[info] 2022-03-29T04:06:01.702401Z node1@127.0.0.1 <0.18373.12> -------- ddoc_cache_entry:terminate St={st,{ddoc_cache_entry_ddocid,{<<"users">>,<<"_design/feature_flags">>}},{open_ok,{not_found,missing}},undefined,undefined,undefined,1}
[error] 2022-03-29T04:06:01.702893Z node1@127.0.0.1 <0.14792.12> -------- gen_server ddoc_cache_lru terminated with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:301) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226)
  last msg: redacted
     state: {st,#Ref<0.4244486069.2877947905.247295>,#Ref<0.4244486069.2877947905.247296>,<0.14791.12>}
    extra: []
[error] 2022-03-29T04:06:01.703080Z node1@127.0.0.1 <0.14792.12> -------- gen_server ddoc_cache_lru terminated with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:301) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226)
  last msg: redacted
     state: {st,#Ref<0.4244486069.2877947905.247295>,#Ref<0.4244486069.2877947905.247296>,<0.14791.12>}
    extra: []
[error] 2022-03-29T04:06:01.703257Z node1@127.0.0.1 <0.14792.12> -------- CRASH REPORT Process ddoc_cache_lru (<0.14792.12>) with 0 neighbors crashed with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:301) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226); initial_call: {ddoc_cache_lru,init,['Argument__1']}, ancestors: [ddoc_cache_sup,<0.4616.0>], message_queue_len: 0, links: [<0.14791.12>,<0.4620.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 29, reductions: 4403
[error] 2022-03-29T04:06:01.703434Z node1@127.0.0.1 <0.14792.12> -------- CRASH REPORT Process ddoc_cache_lru (<0.14792.12>) with 0 neighbors crashed with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:301) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226); initial_call: {ddoc_cache_lru,init,['Argument__1']}, ancestors: [ddoc_cache_sup,<0.4616.0>], message_queue_len: 0, links: [<0.14791.12>,<0.4620.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 29, reductions: 4403
[error] 2022-03-29T04:06:01.703588Z node1@127.0.0.1 <0.4620.0> -------- Supervisor ddoc_cache_sup had child ddoc_cache_lru started with ddoc_cache_lru:start_link() at <0.14792.12> exit with reason no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:301) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226) in context child_terminated
[error] 2022-03-29T04:06:01.703695Z node1@127.0.0.1 <0.4620.0> -------- Supervisor ddoc_cache_sup had child ddoc_cache_lru started with ddoc_cache_lru:start_link() at <0.14792.12> exit with reason no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:301) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226) in context child_terminated
```
In short, any two  `ddoc_cache:open` calls to the same non-existent ddoc that occur close enough in time will cause that error.

**Pull request merged**
