### PR TITLE
Jenkins: update binary platform matrix

### PR DESCRIPTION
**Pull request by wohali**
This PR drops Debian jessie, adds Debian buster, and adds CentOS 8 to the binary platform build matrix on `master`.

### CODE REVIEW

**Comment by wohali** [comment]
Thanks @kocolosk . At some point we should replace the cache of .js packages on that server with direct downloads from our bintray (`http://dl.bintray.com/apache/couchdb-deb/` and `-rpm`)...or at the point when SM60 is supported everywhere upstream, we can drop the entire thing and simplify the process considerably.

**Comment by jiangphcn** [comment]
thanks @wohali for consideration for SM60-related package distribution.

**Comment by wohali** [comment]
@jiangphcn this is still SM1.8.5, I am not yet committing to shipping SM60 for all platforms. But we'll see ;)

**Comment by jiangphcn** [comment]
totally understand @wohali . We can work together to make this happen in the future :-)

**Pull request merged**
