### PR TITLE
Simplify SpiderMonkey couchjs sources

### PR DESCRIPTION
**Pull request by big-r81**
Hi,

I tried to combine and merge the different SpiderMonkey source files together.

During compiling with SM v128 I got the following error message:
```
[1] Compiling /Users/big-r/Documents/Developer/CouchDB/couchdb/src/couch/priv/couch_js/102/util.cpp
/Users/big-r/Documents/Developer/CouchDB/couchdb/src/couch/priv/couch_js/102/util.cpp:327:17: error: invalid operands to binary expression ('std::ostringstream' (aka 'basic_ostringstream<char>') and 'JS::ConstUTF8CharsZ')
            msg << report->filename;
            ~~~ ^  ~~~~~~~~~~~~~~~~

[2] /Users/big-r/Documents/Developer/CouchDB/couchdb/src/couch/priv/couch_js/102/util.cpp:333:49: error: invalid operands to binary expression ('basic_ostream<char, char_traits<char>>' and 'JS::ColumnNumberOneOrigin')
            msg << ':' << report->lineno << ':' << report->column;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
```

I fixed these both errors with the following statements:
```
[1] msg << report->filename.c_str();

[2] msg << ':' << report->lineno << ':' << report->column.oneOriginValue();
```

After that change, I successful compiled against v91, v115 and v128 und run the Fauxton checks!
It seems, that the missing part in all version was the deepFreeze function...

Here is the full log: [error.log](https://github.com/user-attachments/files/17491386/error.log)

### CODE REVIEW

**Comment by janl** [comment]
@big-r81 any objections to merging this to unblock development on macOS and fixing windows at a later stage?

**Comment by big-r81** [comment]
Theoretically yes, the question is, if my “fixes” of the above messages are correct (searching for someone with not c/c++ knowledge).

**Comment by nickva** [comment]
We now have noble with SM 102 and SM 115 https://hub.docker.com/r/apache/couchdbci-ubuntu/tags

**Comment by nickva** [comment]
Noticed a few failures in CI as well:

```
19:23:14  /usr/include/mozjs-102/js/CallArgs.h:137:8: note: by argument 1 of type 'const JS::detail::CallArgsBase<JS::detail::IncludeUsedRval>*' to 'void JS::detail::CallArgsBase<WantUsedRval>::clearUsedRval() const [with WantUsedRval = JS::detail::IncludeUsedRval]' declared here
```

**Comment by nickva** [comment]
Screenshot 2024-12-10 at 12 55 05 AM

Packages are now also working with SM 115 on Ubuntu Noble

**Review by janl — APPROVED** [review]
Let’s go!

**Comment by big-r81** [comment]
No, thx for the reminder 🙏

**Comment by nickva** [comment]
It looks like we broke SM 1.8.5 support here. Thanks to @jiahuili430 for noticing and fixing it in https://github.com/apache/couchdb/pull/5364!

**Pull request merged**
