### PR TITLE
allow socket server configuration for TLS httpd

### PR DESCRIPTION
**Pull request by janl**
The https we optimally start doesn’t read any server options, that prevents users from applying things like `{max, 512}` sockets for mochiweb. This PR adds support for this:

```ini
[httpsd]
server_options = [{max, 512}]
```

### CODE REVIEW

**Comment by wohali** [comment]
minor quibble: I don't know how I feel about using `[chttpsd]` since elsewhere we refer to this daemon just as `[httpsd]`. Are you going to rename the option everywhere?

**Comment by janl** [comment]
Good catch, will fix to the already existing section name.

**Comment by janl** [comment]
Well, turns out, it is `[httpsd]` in the code. I just typo’d it in the description here: https://github.com/apache/couchdb/pull/1424/files#diff-b4ed04bdc6fda9ff5e838def1d1bf7a7R111

**Comment by wohali** [comment]
+1 

Doesn't address #901, which would be nice to fix while you're in this part of the code, but not essential.

**Comment by janl** [comment]
#901 is a lot more complicated to handle, as it is hooked into the architecture completely differently. I’d also argue that folks who need that should bind to 127.0.0.1 and maybe add a firewall setting to block access.

**Pull request merged**
