### PR TITLE
Ensure libmozjs185-dev gets installed.

### PR DESCRIPTION
**Pull request by nickva**
Install libmozjs185-dev

### CODE REVIEW

**Comment by eiri** [comment]
+1

**Comment by kxepal** [comment]
+1. Could you only please remove Try from commit message since it helps?

**Comment by nickva** [comment]
I put "try" in there because it needs another pr:

https://github.com/apache/couchdb-couch/pull/117

to work. By itself it doesn't fix the issue.

**Comment by kxepal** [comment]
Let's pick something neutral then like "Ensure libmozjs 1.8.5 get installed". Still good improvement if one day libmozjs-dev will point on some incompatible version.

**Comment by nickva** [comment]
Agreed. Updated title.

**Comment by kxepal** [comment]
@nickva 
>  Ensure libmozjs185-dev gets installed.
>  Install libmozjs185-dev

There is no need to duplicate the same things (:

**Comment by nickva** [comment]
@kxepal  Sorry, fixed.

**Comment by nickva** [comment]
It looks like libmozjs-dev is a virtual package in Ubuntu 12.04, and it points to mozjs-dev.

http://packages.ubuntu.com/precise/libmozjs-dev

We could still merge it to be explicit which version we require, but it shouldn't affect test results.

**Comment by kxepal** [comment]
Yea, good idea. +1

**Pull request closed without merging**
