### PR TITLE
feat(test): wait for db and index shutdown

### PR DESCRIPTION
**Pull request by janl**
Test branch/PR for https://github.com/apache/couchdb/issues/552#issuecomment-305909995

### CODE REVIEW

**Comment by janl** [comment]
@wohali would be great to give this a spin on Jenkins, but we can equally merge to master and see what happens :)

**Comment by wohali** [comment]
I'd rather not mess with the Jenkins config to build more than just the release branches. Best to just run this specific test in a loop for a few hundred times and see if the error goes away.

**Comment by janl** [comment]
I’ve done a bit, but will set up the loop again and go for dinner, will report back.

**Comment by janl** [comment]
no fail since, +1ing myself :)

**Pull request merged**
