### PR TITLE
Auth tests wip

### PR DESCRIPTION
**Pull request by sebastianrothbucher**
Did some work on cookie_auth and users_db. Unfortunately, deleting user docs seems broken now (you can reproduce it by manually creating one in admin party and trying 2 remove it again). I guess I won't get much further this week, but maybe it helps already... (for more comments and the remaining users_db_security see https://issues.apache.org/jira/browse/COUCHDB-2991)

### CODE REVIEW

**Comment by janl** [comment]
unfortunately this PR creates conflicts on the auth-tests-wip branch, can you rebase?

**Comment by sebastianrothbucher** [comment]
That's strange. My git log shows I'm simply 2 commits ahead of apache:auth-tests-wip (so all seems fine)

**Comment by gldbrzent** [comment]
You are asking people to ignore that the other is spying.  This reeks of a
type of harassment.

Re: unfortunately this PR creates conflicts on the auth-tests-wip branch,
can you rebase

**Comment by gldbrzent** [comment]
The courts mostly attempt to blacklist and black-hole the unsolicited for
these reasons.

**Comment by janl** [comment]
hm, my bad, sorry, thanks for confirming it should work.

**Pull request merged**
