### PR TITLE
2.3.1 Release Proposal

### PR DESCRIPTION
**Pull request by janl**
Mainly to get a CI build status for this set of cherry-picked commits between 2.3.0 and master.

### CODE REVIEW

**Comment by janl** [comment]
needs https://github.com/apache/couchdb-documentation/pull/392

**Comment by janl** [comment]
and https://github.com/apache/couchdb-fauxton/issues/1180

**Comment by wohali** [comment]
Hi @janl ,

I think this one new feature is suitable for 2.3.1;

c5d9cfe570bbb001b0c8af1bc226fc9a24fc8afa (#1766)
(also pull 33e36254d787b38af7144b37fbb83783723a794a)

Would you consider also cherry-picking these minor fixes? These are all small in scope but moderate in covering some corner cases, especially upgrade-related, so I think they'd be good fits for a patch release.

b131fd0558089ffbe18f40e988e33928d1cf8355 (#1786)
25e9e7759223ecccbcb87ac34d4a9d8c56db31ab (#1795, a good speedup)
fcb272ef45063d651b486a5e0098be8b717c8b78 (#1770, closes #1384)
c68863aec58642fc610ede62906609ba6c816a92 (#1808)
587d674582762610fe7cf0fcdfcb563d9b0abcab (#1845, fixes #1841)
c6b095b2ad716b917d260c8a0a56f3d4676ced7f (#1860, fixes mixed-cluster situation)
5269d7967667a5b8b9dfd923bf53d4c1b3ffcfb5 (#1862, subtle bug we've had for years! Relates to #1860)
17f05b758f29a0ec693cf8b72c3bbc3bee300555 (#1874, reported by user in Slack/IRC)
547169447067e9111dbd31f2ae86d49afe980fda (#1880, esp. because this gets replaced in 2.4.0!)

https://github.com/apache/couchdb/pull/1794 which is:
* https://github.com/apache/couchdb/commit/709477d58ae7143eb44d1e14653994dd0aa6f576
* https://github.com/apache/couchdb/commit/8077afbbf1ee78c22c76bb9772c710d8ed0df8a2

https://github.com/apache/couchdb/pull/1824 which is:
* https://github.com/apache/couchdb/commit/88dd1255595b513ff778e5efa4b2399aa3ccb570
* https://github.com/apache/couchdb/commit/632f303a47bd89a97c831fd0532cb7541b80355d

I'd like to see these two land, too:

bfb98104ffd8035b23cabf3b597d68bd91f51b4f (#1868, closes #1053)
e702598c4f2c528a9b867a9989d814cb9f6d8311 (#1905, closes #1899)

But it will probably require you also pull this large (but entirely cosmetic) one as well:
33d4f6d02715a204ef2dd7ddc4795aed5c1b72ce

**Comment by janl** [comment]
Heya @wohali most of these are in. Can you double check and dedupe? :)

**Comment by wohali** [comment]
@janl updated to dedupe, sorry about that, was going off the wrong info

**Comment by janl** [comment]
@wohali thanks for the dedupe, sorry it wasn’t clearer what was included already.

> [c6b095b](https://github.com/apache/couchdb/commit/c6b095b2ad716b917d260c8a0a56f3d4676ced7f) (#1860, fixes mixed-cluster situation)

I may have read things wrong when skimming, but I assumed this was only relevant past the partitioned databases commit. Happy to reconsider if this is generally useful cc @davisp.

> [17f05b7](https://github.com/apache/couchdb/commit/17f05b758f29a0ec693cf8b72c3bbc3bee300555) (#1874, reported by user in Slack/IRC)

I had ruled dep ups for other than critical things to be out of scope for a .1, but on reread I do agree we should do this one.

>#1794 which is: …

felt a bit risqué for a .1, but happy to include.

> #1824 which is: …

Also thought this was moving around things too much for a .1, but am happy to be convinced otherwise (cc @nickva)

* * *

Any I didn’t comment on I agree on adding. Will do so over the weekend while Fauxton gets into shape.

**Comment by wohali** [comment]
@jan thanks. The other we should think about is #1803, but @jaydoane may need help.

**Comment by nickva** [comment]
@janl 

>> #1824 which is: …
> Also thought this was moving around things too much for a .1, but am happy to be convinced otherwise (cc @nickva)

Most changes in the PR was a code move to copy streams logic to its own fabric module in a separate commit:

https://github.com/apache/couchdb/pull/1824/commits/19048fdc9ddae275b02cfb9b1de1c35bcfe94cb0

The main logic was here:

https://github.com/apache/couchdb/pull/1824/commits/41757cd0f8ec48991c0c2fddcb6085b77e636e09

I think it would mostly affect larger clusters with many requests timing out and being cleaned up improperly so they'd leak their rexi workers. The other ones affect might be smaller embedded system with restrictive resource (low max_dbs_open value). But maybe not as critical for average CouchDB deployments and it's a bug that's been there for years, so  I can see keeping it back to reduce the .1 commit set.

Oh and thank you for helping with 2.3.1!

**Comment by janl** [comment]
#1766 and #1824 end up being no trivial merges, so I’ll leave those out for now.

I’ve added everything else.

**Comment by janl** [comment]
#1803 doesn’t look ready yet. cc @jaydoane @iilyak 

I won’t have time to review it, but if it lands in master in the next ~48 hours, I can hold 2.3.1 until then.

**Comment by jaydoane** [comment]
@janl https://github.com/apache/couchdb/pull/1803 has landed in master

**Comment by janl** [comment]
@jaydoane merged, thanks!

**Pull request merged**
