### PR TITLE
Remove couch_auth_cache service

### PR DESCRIPTION
**Pull request by kocolosk**
## Overview

It was only used on the backdoor HTTP port.

## Testing recommendations

Test suite should pass without this service running. Fully expect that some tests will need to be modified / removed, but happy to let Jenkins find them.

## Related Issues or Pull Requests

See #2493 where it manages to cause downtime despite its irrelevancy

## Checklist

- [ ] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by iilyak** [comment]
This is a draft PR so I am assuming it is not yet complete. Are you planing to remove `couch_auth_cache` module itself (or just from supervision tree of a couch application)? 

The reason I ask is because it is mentioned few times in chttpd application.

**Comment by wohali** [comment]
@kocolosk Any chance of getting this in? Would be nice for a 3.2 release, too.

**Comment by kocolosk** [comment]
Good question, I'd entirely forgotten about it. There was a reason it was still in draft, but I think that was mostly fighting with the test suite. Will take a look.

**Comment by kocolosk** [comment]
Seems the first thing to do is see if Nick beat me to the punch over in the other PR :)

**Comment by kocolosk** [comment]
Closing this one in favor #2526. The approach over there preserves the `couch_auth_cache` exported interface to keep things simple but removes the actual caching that was doing more harm than good.

**Pull request closed without merging**
