### PR TITLE
Bump Fauxton to v1.3.0

### PR DESCRIPTION
**Pull request by nickva**

### CODE REVIEW

**Review by big-r81 — APPROVED** [review]
Since, Fauxton uses Node v18, should we bump the version to in the CI images (on a next update cycle)?

**Comment by nickva** [comment]
@big-r81 good call, but I thought we already bumped node in CI images https://github.com/apache/couchdb-ci/pull/63 at least as much as we could bump it. It won't work on centos-7 and bionic

**Comment by pgj** [comment]
Does that mean that Fauxton will not technically work on CentOS 7 and Ubuntu Bionic and this is acceptable?

**Comment by nickva** [comment]
@pgj nodejs is just for building (assembling) the js site bits together. We don't rely on it at runtime. So it probably means we may not be able to build a dist release tarball on centos-7 and bionic.

**Comment by big-r81** [comment]
> @big-r81 good call, but I thought we already bumped node in CI images https://github.com/apache/couchdb-ci/pull/63 at least as much as we could bump it. It won't work on centos-7 and bionic

@nickva oh, you are completely right! Maybe too many good changes at different parts in the last weeks 😉

**Pull request merged**
