### PR TITLE
Bring smoosh in-tree

### PR DESCRIPTION
**Pull request by kocolosk**
## Overview

This adds the auto-compaction daemon directly into the main repo. It also adds the "Support scheduling compactions during time windows" enhancement and related unit tests that were added to couchdb-smoosh after the 1.0.1 tag.

We use git-subtree to carry the smoosh history forward, with an invocation like

```
git subtree add --prefix=src/smoosh https://github.com/apache/couchdb-smoosh.git master
```

## Testing recommendations

Check that the codebase is the same as you would get by moving the "smoosh" tag in rebar to "master".

## Checklist

- [x] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by nickva** [comment]
Doing a local build with `make check` after a `git clean -xffd` and `./configure --dev` I see failures in the boot sequence:

```
{"init terminating in do_boot",{{error,{"no such file or directory","smoosh.app"}},[{boot_node,start_app,3,[{file,"dev/boot_node.erl"},{line,146}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{init,start_em,1,[]},{init,do_boo
t,3,[]}]}}
init terminating in do_boot ({{error,{no such file or directory,smoosh.app}},[{boot_node,start_app,3,[{_},{_}]},{lists,foldl,3,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
Crash dump is being written to: erl_crash.dump...done
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```

**Comment by kocolosk** [comment]
Ah, thanks Nick that definitely points out what I was missing. Hopefully fixed the `rebar.config.script` properly now.

**Comment by loguntsov** [comment]
Hello. There was undefined module call couch_md_index_manager:get_group_pid ( https://github.com/apache/couchdb/pull/2326/files#diff-113cd247cfe56b1aa882a37daa2856fd33bab2e2a6183034eb3a30088960dc13R246 ). Could somebody explain me where i can find this module ?

**Comment by nickva** [comment]
@loguntsov that was an experimental "schema" discovery feature I believe that never made it into a release

In the recent version of main the reference to that module should be removed

**Pull request merged**
