### PR TITLE
Emit heartbeats until feed timeout

### PR DESCRIPTION
**Pull request by kxepal**
COUCHDB-2961

### CODE REVIEW

**Comment by rnewson** [comment]
the heartbeat exists to keep a connection alive so is this a sensible thing to do?

**Comment by kxepal** [comment]
Heartbeats exists to ensure that connection is alive, active and operable, but not to keep it forever (this is actually should be done with timeout=infinity). We cannot relay on protocol level keep-alive because it actually doesn't works as everyone expects and only cause additional hangs (default may be minute to hours). Application level keep-alive is the only way to instantly figure out that things went wrong and time to reconnect. Websockets are effective in unreliable networks because of such approach (ping/pong).

Otherwise we have quite strange case when you do request `GET /db/_changes?feed=continuous&heartbeat=1000&timeout=60000` expecting that timeout will work as usually, but actually it get ignored. That's the first case. Another one is that helps to workaround COUCHDB-2912 issue.

**Comment by wohali** [comment]
@kxepal @rnewson any resolution here?

**Comment by rnewson** [comment]
sorry. @davisp is this right?

**Comment by davisp** [comment]
Only on my phone so not 100% on reading the diff. @kxepal's explanation from a year ago is right as expected behavior. Heartbeat is how often to send a "ping" across the network and timeout is how long to wait for a change and the two should be independent. To my knowledge thats not broken so the change is confusing from that point of view.

If for some reason a heartbeat interval less than the timeout interval keeps a changes feed open forever then we have an issue. I don't see a test asserting the incorrect behavhior though so not sure. And its also possible we fixed this differently in the year since.

**Comment by wohali** [comment]
@kxepal Are you able to help finish this PR?

**Comment by kxepal** [comment]
@wohali oh...it wasnt' merged! On 3th of May will catch it. Thanks for reminder!

**Comment by jlami** [comment]
Any progress on this?

**Comment by janl** [comment]
please reopen if this moves forward.

**Pull request closed without merging**
