### PR TITLE
Fix libicu inconsistency

### PR DESCRIPTION
**Pull request by bessbd**
## Checklist

- [ ] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by bessbd** [comment]
This is related to https://github.com/apache/couchdb/issues/3394

**Comment by nickva** [comment]
It was interesting that we didn't hit this issue on CentOS 7 on 3.x so I was curious and traced the `less` call when running that mango test:

```
10:9:04.429561 <0.11140.1> couch_ejson_compare:less_nif([{<<"ÿÿÿÿ">>}], [{[{<<"forename">>,<<"Eddie">>}]}])

10:9:04.429783 <0.11140.1> couch_ejson_compare:less_nif/2 error badarg

10:9:04.429984 <0.11140.1> couch_ejson_compare:less_erl([{<<"ÿÿÿÿ">>}], [{[{<<"forename">>,<<"Eddie">>}]}])

10:9:04.430254 <0.11140.1> couch_ejson_compare:less_list([{<<"ÿÿÿÿ">>}], [{[{<<"forename">>,<<"Eddie">>}]}])

10:9:04.430506 <0.11140.1> couch_ejson_compare:less_erl({<<"ÿÿÿÿ">>}, {[{<<"forename">>,<<"Eddie">>}]})

10:9:04.430745 <0.11140.1> couch_ejson_compare:less_erl/2 --> 1

10:9:04.430903 <0.11140.1> couch_ejson_compare:less_list/2 --> 1

10:9:04.431088 <0.11140.1> couch_ejson_compare:less_erl/2 --> 1
```

Apparently in `3.x` we compare an object `{[{<<"forename">>,<<"Eddie">>}]}` against a (highest?) marker, but that marker is not an object but a tuple with one element `{<<"ÿÿÿÿ">>}`. `less_nif/2` then notices the object is not valid ejson and throws a `badarg` error.  The the code then falls back to Erlang using `less_erl/2` and at least in this case return the correct result (highest marker is greater than (`1`) than the object).

In `main` we compare against an actual object `{[{<<"ÿÿÿÿ">>, <<>>}]}` so everything gets unpacked nicely then the old unicode library at least older than 59 (and possible 53) didn't error out, but also didn't sort the `<<255,255,255,255>>` as the highest element as intended. Here is centos 7 with libicu-50.2-4.el7_7.x86_64, for example
```
couch_ejson_compare:less(<<"forename">>, <<255,255,255,255>>).
1
> couch_ejson_compare:less(<<"/">>, <<255,255,255,255>>).
-1
> couch_ejson_compare:less(<<"0">>, <<255,255,255,255>>).
1
```

and on mac os with icu4c 59:
```
> couch_ejson_compare:less(<<"forename">>, <<255,255,255,255>>).
-1
> couch_ejson_compare:less(<<"/">>, <<255,255,255,255>>).
-1
> couch_ejson_compare:less(<<"0">>, <<255,255,255,255>>).
-1
```

**Comment by nickva** [comment]
@bessbd I thought we could do a slightly more thorough check for the max string only in C right before we call the collator code https://github.com/apache/couchdb/pull/3490

**Comment by nickva** [comment]
I thought of making a bit more general since noticed we'd have to handle perhaps `less({[?MAX_JSON_OBJ], _}, _) -> gt` and maybe also `{[?MAX_JSON_OBJ], _}, {[?MAX_JSON_OBJ], _} -> eq`. The clause would work currently but if compare a bit differently in the future it might get an unexpected failure. Then there is also the ?HIGHEST_KEY macro which I think is not used in `main` but it may be one day before CentOS 7 is retired and it would unexpectedly fail.

**Comment by bessbd** [comment]
> @bessbd I thought we could do a slightly more thorough check for the max string only in C right before we call the collator code #3490

I responded over at https://github.com/apache/couchdb/pull/3490#issuecomment-812721292

**Comment by bessbd** [comment]
Superseded by https://github.com/apache/couchdb/pull/3490

**Pull request closed without merging**
