### PR TITLE
Update to the latest mrview

### PR DESCRIPTION
**Pull request by eiri**
This includes all the changes made to couch_mrview since the last deps update

### CODE REVIEW

**Comment by eiri** [comment]
@kxepal can you take a look, please? this bumps mrview up to HEAD and should resolve one of those pesky test failures we have on travis.

**Comment by kxepal** [comment]
@eiri
LGFM, except failures on travis. Seems like we have new flaky tests regardless @nickva work /:

IIRC, there were some work in apache/couchdb-couch around delete - does it already on rebar.config?

**Comment by eiri** [comment]
@kxepal Yes, apache/couchdb-couch part got in rebar.config as it happened to be downstream of admin_local work, so mrview's bit got left behind.

The test failures, as far as I can see, are unexpected oauth 403 in `couchdb_vhosts_tests` and timeouts in `couch_changes_tests`. I've seen timeout is `couchdb_compaction_daemon_tests` once, but it seems transient.

**Comment by kxepal** [comment]
@eiri Good then. +1. Those tests need in additional, unrelated work then.

**Pull request merged**
