### PR TITLE
Add chttpd stats

### PR DESCRIPTION
**Pull request by davisp**
## Overview

This adds an advanced API for users that want to write some Erlang to be able to collect request level metrics for reporting.

## Testing recommendations

`make check`

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
This is a huge diff and includes a bunch of partition stuff that might be unrelated?

Can you check that your PR'ed the right thing, and if so, possibly add even developer-level documentation on how this works? I couldn't find the needle in the haystack of 69 changed files.

**Comment by davisp** [comment]
@wohali Sorry, on a meeting and did this half brained and forgot to set the correct base branch. I should have also mentioned I have yet to write an example module for use with this but wanted to have a place for people to start responding to the general idea.

**Comment by wohali** [comment]
Still looks broken @davisp, maybe start again?

**Comment by davisp** [comment]
Sorry. I've been updating the other PRs and it gets all weird. Soon as the partition limit PR is merged here in a bit I'll update this to be off master so that its not constantly getting all weird.

**Comment by davisp** [comment]
Fixed

**Pull request merged**
