### PR TITLE
Consolidate elixir targets and simplify Makefile

### LINKED ISSUE #3824: Consolidate various elixir makefile targets
## Summary

If anyone is interested in consolidating the elixir, elixir-only, and elixir-suite into a single target I'm all ears. The first two are identical save for the `MIX_ENV` and `COUCHDB_TEST_ADMIN_PARTY_OVERRIDE` environment settings, so I'm guessing we only need one target. The last one uses a skip file instead of the `@pending` tag; I'm not sure we need two distinct approaches there.

## Desired Behaviour

A simpler, more obvious Makefile

## Additional context

Originally reported in #3818

### PR DESCRIPTION
**Pull request by kocolosk**
## Overview

This PR is really just trying to simply our Makefile, reducing target overlap and removing unnecessary environment declarations and dependencies. I also restored `python-black` as a required check and reformatted our Python code accordingly.

## Testing recommendations

* `make check` covers everything changed here
* `make elixir-suite` has been streamlined a bit but still runs the full integration suite
* `make elixir-check-formatted`, `make elixir-credo`, and `make elixir-integration` can all be run independently. They no longer depend on `elixir-init`, so if you're working on a clean instance `mix` will ask you if you want to install rebar etc. locally (and you can just accept the default)
* `make mango-test` also saw a few small changes.

## Reviewer Guidance

The commits are meant to be reviewed individually. Most are quite straightforward, but looking at the diff in its entirety can make it more difficult to figure out some of the substance. Other noteworthy bits:

* I removed the `TEST_OPTS` variable -- does anyone use it at all? Inside the Makefile it was being used to inject some .ini config settings; I moved those to an appropriate `test-config.ini` file.
* The `suite.elixir` file was a bit outdated, so I rebuilt it. I also renamed two tests that were being accidentally excluded from the suite.
* The `skip.elixir` file was skipping several tests that actually pass, and was not excluding any tests that were not already marked with a `pending` tag. I zeroed out the skip file in this PR and left a comment that it could be used if one wanted to exclude tests without tagging them directly in the codebase.

## Discussion Topic

I find it a little janky to have to keep `suite.elixir` manually up-to-date. Should we find a way to automate that? I found quite a few instances in today's work where we were not running tests that we ought to have been running. Conversely, do we actually need to keep the suite / skip approach to managing test sets? ExUnit always has a fairly rich tagging and filtering system for constructing test sets. I wouldn't mind at all if e.g. Cloudant folks wanted to add some additional tags to tests so they could exclude / include them as needed for their internal CI setup.

## Related Issues or Pull Requests

Closes #3824

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by jaydoane** [comment]
> I find it a little janky to have to keep suite.elixir manually up-to-date.

Same.

> Should we find a way to automate that?

The default behavior of `mix` is to run all tests, so if an up to date suite.elixir would just contain the full list of tests anyhow, I don't know why we couldn't just get rid of suite.elixir and the `--include` line that references it entirely. The only case I can think of that it would be useful is when you want to define a very small set of tests to run (e.g. the quorum tests), which would be harder to do just using exclusion. But it seems like we're just using normal tags for that, so who knows.

> Conversely, do we actually need to keep the suite / skip approach to managing test sets? ExUnit always has a fairly rich tagging and filtering system for constructing test sets. I wouldn't mind at all if e.g. Cloudant folks wanted to add some additional tags to tests so they could exclude / include them as needed for their internal CI setup.

I don't remember the exact requirements that led @iilyak to the current design, but if Cloudant had the ability to add tags, we could maybe dispense with the skip approach.

**Review by jaydoane — APPROVED** [review]
Typo in a commit 2 message: "repreatedly".

This seems like a really nice improvement!

I also wonder if how much of the suite/skip mechanism is strictly necessary, but I have found the skip file useful at least. I think maybe we can eliminate `elixir.suite` and just run all tests mix can find be default, and exclude them explicitly by one means or another.

**Comment by kocolosk** [comment]
Thanks Jay! I hadn't seen your approval before I dropped that last commit on this PR, so I can revert it for now and file it as a separate, standalone PR. I'll fix the typo as well.

The code that generates `suite.elixir` takes about 15 seconds to execute on my machine, so I'd want to see if there was a better way to optimize that before running that routine on-demand as part of a Makefile target. I think the idea of constructing a set of excludes from the contents of a `skip.elixir` file instead of generating input to the `only_test_ids` argument could be a good approach.

**Comment by kocolosk** [comment]
I discovered that the module and test name are automatically [injected](https://github.com/elixir-lang/elixir/blob/79cd891eb86ecb7654a7acdb63769cfdd950a5c0/lib/ex_unit/lib/ex_unit/runner.ex#L261) as tags on each test. That means we could exclude tests by name, or exclude an entire module, but I don't think we'd be able to exclude based on a qualified `{module, test_name}` tuple.

We do have some duplicate test names in different modules but that wouldn't be too difficult to rectify.

**Comment by kocolosk** [comment]
I'm going to merge this one now and file a separate PR if/when we reach consensus on improvements to the suite.elixir setup in #3824

**Pull request merged**
