### PR TITLE
Import couchdb setup

### PR DESCRIPTION
**Pull request by janl**
PR for https://github.com/apache/couchdb/issues/566

### CODE REVIEW

**Comment by janl** [comment]
not sure why GitHub complains here, the branch merges cleanly locally.

**Comment by janl** [comment]
cc @davisp review plz <3

**Comment by davisp** [comment]
+1

Look fine to me. Though you'll want to update rebar.config.script after you merge this. As to the conflicts notice it sure would be nice to know what GitHub thinks is in conflict. Assuming it applies cleanly locally I'd just do that and call it good. It could even be that GitHub thinks its a conflict precisely because they have separate roots.

**Comment by wohali** [comment]
@janl A reminder this needs to be updated for the latest changes to couchdb-setup that I just pushed.

**Comment by wohali** [comment]
bump. we should do this.

**Comment by davisp** [comment]
@wohali Says merged or am I missing something else?

**Comment by wohali** [comment]
@davisp That's a different PR. This is definitely not done, otherwise we'd have a /src/setup directory in this repo, and we don't.

**Comment by davisp** [comment]
@wohali Let that be a lesson for me to never read through PR activity before my first coffee.

**Comment by wohali** [comment]
@jan any desire to get this onto master (and thus 2.1.x)?

**Comment by wohali** [comment]
Superceded by #1241.

**Pull request closed without merging**
