### PR TITLE
Add global handler for delegated auth

### PR DESCRIPTION
**Pull request by janl**

### CODE REVIEW

**Comment by janl** [comment]
This is the 2.x version of https://github.com/apache/couchdb/pull/366

Goes with:
- https://github.com/apache/couchdb-chttpd/pull/97
- https://github.com/apache/couchdb-couch/pull/132

**Comment by wohali** [comment]
@janl I'd love to see this land...but I lack the time and experience to review your PR. Perhaps you could pressure someone else into looking into this and merging it? I hate seeing good ideas wither on the vine (and really don't want to see PRs >1 year old sitting on our repos...)

**Comment by wohali** [comment]
@janl Hey, can you merge apache/couchdb-chttpd#97 and apache/couchdb-couch#132 into this PR now that we have a monorepo?

Also, any chance of a test? ;)

**Comment by wohali** [comment]
The alternative is we do code clearance and merge https://github.com/cloudant/delegated_auth instead. /cc @eiri @rnewson

**Comment by wohali** [comment]
Ping. Cleaning up old stuff. Any interest in reviving this or instead taking https://github.com/cloudant/delegated_auth

**Comment by rnewson** [comment]
no interest from me.

**Comment by BigBlueHat** [comment]
@wohali looks like `delegated_auth` needs an open source license first (at least). I'll let @janl (et al) handle the other bits. 😃

**Pull request closed without merging**
