### PR TITLE
Add testing for http API status code responses in different quorum conditions

### PR DESCRIPTION
**Pull request by jjrodrig**
## Overview

Add testing for http API status code responses in different quorum conditions

## Testing recommendations
```
make test-cluster-with-quorum
make test-cluster-without-quorum
```

## Related Issues or Pull Requests

Covers the testing described in  #1156 

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
@janl do we _really_ want to add a bunch of new couchjs-based tests at this point? I am -0.5.

**Comment by janl** [comment]
@wohali this is stuff we are not testing at the moment and the Elixir tests are still being filled out, so why not? :)

**Comment by wohali** [comment]
as I said I won't block, I'm glad for more tests, I'd just prefer them to be in Elixir :)

**Comment by janl** [comment]
Thank you!

**Pull request merged**
