### PR TITLE
Ignore javascript test suites

### PR DESCRIPTION
**Pull request by tonysun83**
## Overview

This PR enhances allows developers to ignore javascript test suites with the new option
ignore_js_suites.

Example usage:

make javascript ignore_js_suites="all_docs basics"
make javascript suites="all_docs basics view_errors" ignore_js_suites=
"view_errors"

The second example is redundant but the functionality works.

## Testing recommendations
Try variations of make javascript with suites= and ignore_js_suites=

## Related Issues or Pull Requests
The issue is this PR

## Checklist

- [X] Code is written and works correctly;
- [X] Changes are covered by tests;
- [x] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
What is the use case here? I'm baffled.

**Comment by tonysun83** [comment]
@wohali : One use case I imagined is where developers would like use the javascript test suite to provide more test coverage while they develop new features. The feature could be breaking tests due to some integration issue (waiting on another developer's commit/feature). Knowing the issue, the developer wants to ignore the test and be at least confident that other tests are not failing due to other regression issues.

**Comment by wohali** [comment]
You can run individual JS tests already. Do you see a need to be able to run "all but some" and not just "only run these few tests I actively care about?"

**Comment by tonysun83** [comment]
I think it would be good to have the capability to run "all but some".  I know for the eunit tests we have skip_deps, which is different in approach as it skips apps, but I wanted something with similar functionality. It provides a better feeling of robustness for any new feature development.

**Comment by nickva** [comment]
I like this. Seems symmetric with skip apps / deps

**Comment by janl** [comment]
agree this would be neat, but didn’t get it at first like @wohali. I too like the symmetry. Either way, whatever helps make running tests more comfortable :)

**Comment by janl** [comment]
@tonysun83 wanna add a few lines of docs to https://github.com/apache/couchdb/blob/master/README-DEV.rst#testing +1 afterwards

**Pull request merged**
