### PR TITLE
feat: update couch_peruser for 2.0 patch by @guillett

### PR DESCRIPTION
**Pull request by janl**
## Overview

couch_peruser was built to follow a node-local _changes feed instead of the clustered _changes feed.

This patch by @guillett fixes this: https://github.com/apache/couchdb-peruser/pull/3

Moving this over because couch_peruser has been moved to couchdb.git

## Related Pull Requests

https://github.com/apache/couchdb-peruser/pull/3

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [x] Documentation reflects the changes;

### CODE REVIEW

**Comment by janl** [comment]
cc @guillett

**Comment by jamescorbett** [comment]
Just tried this, worked great first time. On restart I'm getting a crash.
```[info] 2017-06-05T08:24:17.964899Z nonode@nohost <0.198.0> -------- Starting couch_sup
[error] 2017-06-05T08:24:18.100303Z nonode@nohost <0.234.0> -------- CRASH REPORT Process  (<0.234.0>) with 0 neighbors exited with reason: bad argument in call to ets:member(mem3_openers, <<"_users">>) at mem3_shards:maybe_spawn_shard_writer/3(line:486) <= mem3_shards:load_shards_from_db/2(line:389) <= mem3_shards:load_shards_from_disk/1(line:378) <= mem3_shards:for_db/2(line:59) <= mem3_shards:local/1(line:156) <= couch_peruser:init/0(line:58) <= couch_peruser:init/1(line:187); initial_call: {couch_peruser,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.197.0>], messages: [], links: [<0.206.0>,<0.83.0>], dictionary: [], trap_exit: false, status: running, heap_size: 4185, stack_size: 27, reductions: 3938
[error] 2017-06-05T08:24:18.100543Z nonode@nohost <0.206.0> -------- Supervisor couch_secondary_services had child couch_peruser started with couch_peruser:start_link() at undefined exit with reason bad argument in call to ets:member(mem3_openers, <<"_users">>) at mem3_shards:maybe_spawn_shard_writer/3(line:486) <= mem3_shards:load_shards_from_db/2(line:389) <= mem3_shards:load_shards_from_disk/1(line:378) <= mem3_shards:for_db/2(line:59) <= mem3_shards:local/1(line:156) <= couch_peruser:init/0(line:58) <= couch_peruser:init/1(line:187) in context start_error
[error] 2017-06-05T08:24:18.101403Z nonode@nohost <0.198.0> -------- Supervisor couch_sup had child couch_secondary_services started with couch_secondary_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,couch_peruser,{badarg,[{ets,member,[mem3_openers,<<"_users">>],[]},{mem3_shards,maybe_spawn_shard_writer,3,[{file,"src/mem3_shards.erl"},{line,486}]},{mem3_shards,load_shards_from_db,2,[{file,"src/mem3_shards.erl"},{line,389}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,378}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,59}]},{mem3_shards,local,1,[{file,"src/mem3_shards.erl"},{line,156}]},{couch_peruser,init,0,[{file,...},...]},...]}}} in context start_error
[error] 2017-06-05T08:24:18.101486Z nonode@nohost <0.197.0> -------- Error starting Apache CouchDB:

    {error,{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,couch_peruser,{badarg,[{ets,member,[mem3_openers,<<"_users">>],[]},{mem3_shards,maybe_spawn_shard_writer,3,[{file,"src/mem3_shards.erl"},{line,486}]},{mem3_shards,load_shards_from_db,2,[{file,"src/mem3_shards.erl"},{line,389}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,378}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,59}]},{mem3_shards,local,1,[{file,"src/mem3_shards.erl"},{line,156}]},{couch_peruser,init,0,[{file,"src/couch_peruser.erl"},{line,58}]},{couch_peruser,init,1,[{file,"src/couch_peruser.erl"},{line,187}]}]}}}}}}


[error] 2017-06-05T08:24:18.101983Z nonode@nohost <0.196.0> -------- CRASH REPORT Process  (<0.196.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,couch_peruser,{badarg,[{ets,member,[mem3_openers,<<"_users">>],[]},{mem3_shards,maybe_spawn_shard_writer,3,[{file,"src/mem3_shards.erl"},{line,486}]},{mem3_shards,load_shards_from_db,2,[{file,"src/mem3_shards.erl"},{line,389}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,378}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,59}]},{mem3_shards,local,1,[{file,"s..."},...]},...]}}}}},...} at application_master:init/4(line:133) <= proc_lib:init_p_do_apply/3(line:237); initial_call: {application_master,init,['Argument__1','Argument__2',...]}, ancestors: [<0.195.0>], messages: [{'EXIT',<0.197.0>,normal}], links: [<0.195.0>,<0.7.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 27, reductions: 158
[info] 2017-06-05T08:24:18.102835Z nonode@nohost <0.7.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,couch_peruser,{badarg,[{ets,member,[mem3_openers,<<"_users">>],[]},{mem3_shards,maybe_spawn_shard_writer,3,[{file,"src/mem3_shards.erl"},{line,486}]},{mem3_shards,load_shards_from_db,2,[{file,"src/mem3_shards.erl"},{line,389}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,378}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,59}]},{mem3_shards,local,1,[{file,"s..."},...]},...]}}}}},...}
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,couch,{{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,couch_peruser,{badarg,[{ets,member,[mem3_openers,<<\"_users\">>],[]},{mem3_shards,maybe_spawn_shard_writer,3,[{file,\"src/mem3_shards.erl\"},{line,486}]},{mem3_shards,load_shards_from_db,2,[{file,\"src/mem3_shards.erl\"},{line,389}]},{mem3_shards,load_shards_from_disk,1,[{file,\"src/mem3_shards.erl\"},{line,378}]},{mem3_shards,for_db,2,[{file,\"src/mem3_shards.erl\"},{line,59}]},{mem3_shards,local,1,[{file,\"src/mem3_shards.erl\"},{line,156}]},{couch_peruser,init,0,[{file,\"src/couch_peruser.erl\"},{line,58}]},{couch_peruser,init,1,[{file,\"src/couch_peruser.erl\"},{line,187}]}]}}}}},{couch_app,start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,couch,{{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,couch_peruser,{badarg,[{e```

Build was based on: https://github.com/klaemo/docker-couchdb/blob/master/2.0.0/Dockerfile with this git branch instead of the tar from apache

**Comment by janl** [comment]
@jamescorbett can you paste the full log? I can’t seem to be able to reproduce this in the source tree

**Comment by wohali** [comment]
Would love to see this in 2.1.0 as well. @jamescorbett are you able to consistently reproduce this against our master branch?

**Comment by wohali** [comment]
Bunch of warnings in the test that should be cleaned up prior to merging:

```
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:209: Warning: a term is constructed, but never used
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:210: Warning: a term is constructed, but never used
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:226: Warning: a term is constructed, but never used
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:227: Warning: a term is constructed, but never used
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:250: Warning: a term is constructed, but never used
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:251: Warning: a term is constructed, but never used
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:274: Warning: a term is constructed, but never used
/home/travis/build/apache/couchdb/src/couch_peruser/test/couch_peruser_test.erl:275: Warning: a term is constructed, but never used
```

**Comment by wohali** [comment]
Never mind, we have a bunch of these in the test code, mostly on these `?_assert()` lines where I think it's a spurious error. I believe these can be ignored safely.

**Comment by jahtalab** [comment]
When do you plan to release this fix?

**Comment by wohali** [comment]
In the next two weeks.

**Comment by rasdaniil** [comment]
Hi
Can't underestimate how crucial this fix is
Would it be possible now to install Couchdb with this fix included?
Thanks

**Comment by rasdaniil** [comment]
Thanks, I've managed to compile it

**Pull request merged**
