### PR TITLE
Remove exunit makefile target

### PR DESCRIPTION
**Pull request by nickva**
We don't have any exunit tests any longer but still spend time setting up and running exunit tests in CI.

### CODE REVIEW

**Review by big-r81 — DISMISSED** [review]
Thx Nick.

Please remove it from Makefile.win too, if it exists.

**Comment by nickva** [comment]
@big-r81 the pr has it removed already :-)  https://github.com/apache/couchdb/pull/4845/files#diff-10ed172a506448a217903c4ff9ddc9e6044d176b8d3ff409a59602494cf2397dL143-L175

**Comment by big-r81** [comment]
🫣

**Review by big-r81 — APPROVED** [review]
+1

**Pull request merged**
