### PR TITLE
Move elixir search tests with other elixir tests

### PR DESCRIPTION
**Pull request by jaydoane**
## Overview

Now that dreyfus is integrated into CouchDB, its elixir tests can be moved with the other elixir integration tests, while removing some extra configuration.

## Testing recommendations

```
make elixir-search
```
will run the search tests, which should all fail returning 503 if clouseau is not running:
```
Finished in 2.5 seconds (0.00s async, 2.5s sync)
26 tests, 26 failures
```

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] Documentation changes were made in the `src/docs` folder
- [ ] Documentation changes were backported (separated PR) to affected branches

### CODE REVIEW

**Comment by nickva** [comment]
+1 if it passes tests

**Comment by pgj** [comment]
@jaydoane thanks for improving my work further!  In retrospect, now I see that the version I originally created was a bit clumsy, it should already have been like you did.

I was able to run Clouseau locally, so please find the test results below when Clouseau is running (all the irrelevant parts of the output is omitted):

```console
$ make elixir-search
[..]
SearchTest [test/elixir/test/search_test.exs]
  * test search returns all items for POST (404.7ms) [L#126]
  * test clean up search index with invalid design document (110.8ms) [L#217]
  * test drilldown multiple query definitions for POST (145.4ms) [L#204]
  * test drilldown multiple keys multiple values for POST (155.0ms) [L#191]
  * test drilldown single key multiple values for GET (129.1ms) [L#86]
  * test drilldown multiple query definitions for GET (156.2ms) [L#112]
  * test drilldown single key single value for POST (174.8ms) [L#139]
  * test drilldown multiple keys single values for POST (137.1ms) [L#165]
  * test search returns all items for GET (133.9ms) [L#60]
  * test drilldown three keys single values for POST (155.2ms) [L#178]
  * test drilldown single key single value for GET (147.1ms) [L#73]
  * test drilldown single key multiple values for POST (152.8ms) [L#152]
  * test drilldown multiple keys single values for GET (148.9ms) [L#99]
[..]
PartitionSearchTest [test/elixir/test/partition_search_test.exs]
  * test Cannot do global query with partition view (86.1ms) [L#134]
  * test restricted parameters are not allowed in query or body (92.0ms) [L#221]
  * test rejects conflicting partition values (187.1ms) [L#210]
  * test normal search on non-partitioned dbs with over limit (142.0ms) [L#199]
  * test Works with bookmarks and limit (169.9ms) [L#84]
  * test Works with limit using POST for partitioned db (193.5ms) [L#123]
  * test Cannot do partition query with global search ddoc (87.1ms) [L#147]
  * test normal search on non-partitioned dbs without limit (144.1ms) [L#173]
  * test Simple query returns partitioned search results (188.1ms) [L#52]
  * test normal search on non-partitioned dbs with limit (151.0ms) [L#186]
  * test Only returns docs in partition not those in shard (137.4ms) [L#71]
  * test normal search on non-partitioned dbs still work (246.2ms) [L#160]
  * test Works with limit using POST for on non-partitioned db (140.8ms) [L#112]
[..]
Finished in 6.7 seconds (0.00s async, 6.7s sync)
26 tests, 0 failures
```

**Review by pgj — CHANGES_REQUESTED** [review]
Please remember to apply the changes in `Makefile` to [`Makefile.win`](https://github.com/apache/couchdb/blob/main/Makefile.win#L245-L254) as well.  The developer instructions ([`README-DEV.rst`](https://github.com/apache/couchdb/blob/main/README-DEV.rst#testing)) should also be updated.

**Comment by pgj** [comment]
I can confirm that the `elixir-search` target works on Windows as expected.

**Pull request merged**
