### PR TITLE
Add couch_stats tracking back to couch_log

### PR DESCRIPTION
**Pull request by jiangphcn**
## Overview

Add couch_stats tracking back to couch_log using stats defined in
https://github.com/apache/couchdb/blob/master/src/couch_log/priv/stats_descriptions.cfg
## Testing recommendations

```
jiangphs-mbp-2:dev jiangph$ ./remsh
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V7.2.1  (abort with ^G)
(node1@127.0.0.1)1> couch_stats:sample([couch_log, level, debug]).
169
(node1@127.0.0.1)2> couch_stats:sample([couch_log, level, info]).
13
(node1@127.0.0.1)3> couch_stats:sample([couch_log, level, notice]).
37
(node1@127.0.0.1)4> couch_stats:sample([couch_log, level, warning]).
1
(node1@127.0.0.1)5> couch_stats:sample([couch_log, level, error]).
0
(node1@127.0.0.1)6> couch_stats:sample([couch_log, level, critical]).
0
(node1@127.0.0.1)7> couch_stats:sample([couch_log, level, alert]).
0
(node1@127.0.0.1)8> couch_stats:sample([couch_log, level, emergency]).
0
```

```
make check skip_deps+=couch_epi apps=couch_log

...
[0.183 s] ok
  [done in 0.196 s]
module 'couch_log_test_util'
module 'couch_log_app'
module 'couch_log_config'
module 'couch_log_config_dyn'
module 'couch_log_formatter'
module 'couch_log_error_logger_h'
module 'couch_log_trunc_io_fmt'
module 'couch_log_monitor'
module 'couch_log_server'
module 'couch_log_sup'
module 'couch_log_util'
module 'couch_log_writer_file'
module 'couch_log_writer_syslog'
module 'couch_log_writer_stderr'
module 'couch_log'
module 'couch_log_writer'
=======================================================
  All 155 tests passed.
```
## Related Issues or Pull Requests

issue #832

## Checklist

- [X] Code is written and works correctly;
- [X] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by eiri** [comment]
This change creates a circular dependency. With it `couch_log` now depends on `couch_stats` to start first (_which need, btw, to be reflected in `couch_log.app.src`_), but `couch_stats` is using `couch_log` and depends on it [to be started first](https://github.com/apache/couchdb/blob/master/src/couch_stats/src/couch_stats.app.src#L17).

**Comment by davisp** [comment]
Historically we've just handwaved off these sorts of things as they only cause problems during the bootsequence if something else has gone wrong. However, looking into this particular case it seems like it would be better to remove the couch_log dependency from couch_stats as its a relatively minor usage.

Also to break the cycle we can swap couch_stats to message error_logger directly in the places where that makes sense (which I think is just one for the unknown metric message).

**Comment by jiangphcn** [comment]
Below is from output from `couch_stats`.

```
jiangphs-mbp-2:dev jiangph$ ./remsh
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V7.2.1  (abort with ^G)
(node1@127.0.0.1)1> couch_stats:increment_counter([couchdb, httpd, unknown]).
{error,unknown_metric}
(node1@127.0.0.1)2>
=ERROR REPORT==== 14-Dec-2017::13:49:37 ===
unknown metric: [couchdb,httpd,unknown]** at node node1@127.0.0.1 **
```

**Comment by eiri** [comment]
lgtm. wait on +1 from @davisp though

**Pull request merged**
