### PR TITLE
Stop replications on target document write failures

### PR DESCRIPTION
**Pull request by nickva**
Previously when target document writes failed, because a VDU prevented the
write, or it exceed size limits on the target cluster, replication continued
and a `doc_write_failures` statistic counter was incremented. The counter was
visible in _active_tasks output for continuous replications and was visible in
the completion record written back to the replication documents.

That behavior might not be suitable in many cases. For instance, when migrating
data, if the counter is ignored by the user, combined with a successful
replication completion could lead to a perceived data loss. Until recently
00b28c265d97df675b725cd68897dc371cbd7168 this was even worse because on
replication scheduler would reset statistics counters on every job start. So if
a job restarted at least once, user might never find out that all their data
didn't copy from the source to the target.

Introduce a replicator config `stop_on_doc_write_failure = true | false` where
the replication crashes if a single document write fails. This will many write
failures visible to the and they would know exactly which document failed and
why.

Replications which crash because of doc write failures would retry periodically
just like any other crashes related to missing source or target connectivity,
for example. They do not fail permanently because users could adjust document
size limit on a target cluster or change the VDU function and then replication
will start working again and complete. Here we rely on exponential backoffs
which were introduced with the scheduling replicator work. At the maximum
backoff interval replications would retry about once every 8 hours.

After the failure is handled and bubbles up to the main replication job process,
there is an attempt to checkpoint before exiting with the error. That is done
in order to reduce change feed reprocessing during each retry attempt.

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;
   Will make a separate PR for documentation

### CODE REVIEW

**Comment by nickva** [comment]
One thing we should do is have this to be per-replication task like other replication options.

**Comment by rnewson** [comment]
-1 from me. As you note, there are many legitimate reasons for a document write to fail and for the replication to continue regardless. Making replication even more complicated by adding a new mode of operation is not a step in the right direction.

Instead, I think we should be showing these things more clearly. If the count of failed writes is not persisted, it should be. If it doesn't explain the reasons, it should (vdu_rejections: 4, doc_too_large: 5, etc, etc).

**Comment by wohali** [comment]
I think the fundamental problem you're trying to solve here is surfacing the failures to the user.

Currently the replication status fields aren't rich enough to capture "Succeeded, but with errors" as a new end state. I would argue strongly that we need that state, that Fauxton needs to display it in a different colour, and that the specific types of failures should be enumerated (along with the total # of documents that _successfully_ replicated).

Note as well that continuous replications could be in a "Succeeding/running, but with errors" state as well that should be called out.

The problem is that client code needs to be rewritten. Many replication monitoring scripts that I've run into in the wild tend to be of the sort "start the replication, check `/_active_tasks` or `scheduler/jobs`, if not errored, everything is fine, when it hits succeeded, we're good." Those scripts will have to be taught to react to the new state.

-----

At the very least, failing on a single document write seems overkill. If this proposal is to proceed, I'd recommend changing your setting to:

```
stop_on_doc_write_failure = false ; current behaviour
stop_on_doc_write_failure = ### ; stops after ### failures occur
stop_on_doc_write_failure = true ; same as = 1
```

-----


Either way, this is too big of a change to go into 2.3.0 (which is imminent) so I'd ask you to hold off on merging this PR for now if approved. If I had to express a numerical opinion, it'd be -0.

**Comment by nickva** [comment]
@rnewson 

> there are many legitimate reasons for a document write to fail and for the replication to continue regardless. 

The `continue regardless` thing is what this is mostly about, it configures where continuing should happen or shouldn't happen. Once it continues and checkpoints it's a headache to retry it (delete checkpoints on target and source, create / update the replication document, get another error, do the same thing again, etc). A replication "successfully" completing is misleading the user as well in  a way and can be perceived as a "data loss".

>  If the count of failed writes is not persisted, it should be. 

We fixed that recently and now is persisted between job runs (before it wasn't) but persisting it to the replication doc would invite more updates to doc which were trying to move away from, especially with continuous replications. We could persist it to the the checkpoint history, we already save it there. But we'd have to checkpoint and retrying the replication would involve all the hassle as described above. We could invent some other, new place to persist replication state (new type of local replicator docs).

I am not against adding more detailed counts, but that could orthogonal to the idea of stopping a replication job of failure. The downside is that it doesn't help with knowing which document failed and why. So even then, fixing it means doing a diff between databases or scouring log files.

**Comment by wohali** [comment]
I'd remind both of you that if this is a discussion that bears more thought, it'd be best to take it to `dev@couchdb.apache.org` and not discuss it in this PR, please.

**Comment by nickva** [comment]
@wohali 

> I would argue strongly that we need that state, that Fauxton needs to display it in a different colour

With doc_write_failures count we have that state. I think we could improve Fauxton to highlight the replication line in yellow.

> The problem is that client code needs to be rewritten. Many replication monitoring scripts that I've run into in the wild tend to be of the sort "start the replication, check /_active_tasks or scheduler/jobs, if not errored, everything is fine, when it hits succeeded, we're good."

Exactly, that complicates the state machine (that blue / yellow diagram we have) a bit as well. That is why I proposed this PR: it keeps the states the same, it identifies which document failed and why, and if the error condition is fixed, it will eventually complete successfully. 

>  If this proposal is to proceed, I'd recommend changing your setting to:

```
stop_on_doc_write_failure = false ; current behaviour
stop_on_doc_write_failure = ### ; stops after ### failures occur
```

Or just call it max_doc_write_failures? and make it infinity or integer with 0 being equivalent to true currently. That might work. The problem then is users still won't  know which document failed to fix it, and it would be somewhat indeterministic depending on the order in which replication workers write. I think in general there would be a sharp binary choice between users who say migrate their data and would not tolerate returning "success" of all their data didn't copy over vs users who expect doc write rejects, then they'd be ok with the default (infinity or false in this case).

Another option is to allow max per/failure type counts. Max vdu fails, max attachment size fails, etc.

**Comment by nickva** [comment]
Added per-replication job configuration. 

To manually play with it and test refer to this script:

https://gist.github.com/nickva/8dacbda953db77292d864f59af2d6d2c

* Create a source, add a 10k doc to it
* Set `max_document_size = 10000`
* Set `stop_on_doc_write_failures = true`
* Create a replication
* Check `_scheduler/docs` for state:
  * If set stop_on_doc_write_failures = true is should stop with:
    ```"{doc_write_failure,\"<docid>\", {error,request_body_too_large}}",```
   crashed state.  It should not complete.
* Reset the document size limit, wait for the replication to complete (there is a quicker reschedule step in the file).

**Comment by brianewilkins** [comment]
The replication of a document silently fails if the sum of the sizes of its attachments is high enough. There is no indication of which documents failed to replicate or why.

Below is a sequence of commands to reproduce the problem using Cloudant.
When you run this sequence of commands the variables ACCOUNTNAME and PASSWORD must have been set to appropriate values.
```
SOURCE_DB=https://$ACCOUNTNAME:$PASSWORD@$ACCOUNTNAME.cloudant.com/fb110773_source
TARGET_DB=https://$ACCOUNTNAME:$PASSWORD@$ACCOUNTNAME.cloudant.com/fb110773_target
REPLICATOR_DB=https://$ACCOUNTNAME:$PASSWORD@$ACCOUNTNAME.cloudant.com/_replicator

ATTACHMENT_FILE=attachment_file
ATTACHMENT_MIME_TYPE=application/octet-stream

curl -X DELETE $SOURCE_DB
curl -X DELETE $TARGET_DB

curl -X PUT $SOURCE_DB
curl -X PUT $TARGET_DB

dd if=<(yes | tr -d "\n") of=$ATTACHMENT_FILE bs=1024 count=10240 # create a 10 MB file

REV=`curl -X PUT $SOURCE_DB/doc1 -H "Content-Type: application/json" -d {} | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc1/attachment1?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc1/attachment2?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc1/attachment3?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc1/attachment4?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc1/attachment5?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc1/attachment6?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc1/attachment7?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`

REV=`curl -X PUT $SOURCE_DB/doc2 -H "Content-Type: application/json" -d {} | jq .rev | tr -d '"'`
REV=`curl -X PUT $SOURCE_DB/doc2/attachment1?rev=$REV -H "Content-Type: $ATTACHMENT_MIME_TYPE" -d @$ATTACHMENT_FILE | jq .rev | tr -d '"'`

curl -X PUT $REPLICATOR_DB
REPLICATOR_DOCID=fb110773_`date +%Y%m%d_%H%M%S`
curl -X PUT $REPLICATOR_DB/$REPLICATOR_DOCID -H "Content-Type: application/json" -d "
{
  \"source\": \"$SOURCE_DB\",
  \"target\": \"$TARGET_DB\"
}"

sleep 30

curl -s $TARGET_DB/_all_docs
curl -s $REPLICATOR_DB/$REPLICATOR_DOCID?include_docs=true | jq .
```

When you run that sequence of commands the document doc2, whose attachment size is no more than 10 MB, is replicated to the target database. But the document doc1 is not replicated to the target database, and that must be because the sum of the size of its attachments exceeds the effective value of httpd/max_http_request_size. 
What is problematic is that it fails silently to replicate:
1) The "_replication_state" of the _replicator document is not an error state.
2) There is no indication of which documents failed to replicate or why.

Here is what the _replicator document eventually became (except that I have replaced my password with <password_redacted>):
```
$ curl -s $REPLICATOR_DB/$REPLICATOR_DOCID?include_docs=true | jq .
{
  "_id": "fb110773_20181102_003011",
  "_rev": "5-9d892a5b73b8099960ff97277a283f6c",
  "source": "https://44d7fc0c-fa43-48d8-a86e-c4d4d19dea62-bluemix:<password_redacted>@44d7fc0c-fa43-48d8-a86e-c4d4d19dea62-bluemix.cloudant.com/fb110773_source",
  "target": "https://44d7fc0c-fa43-48d8-a86e-c4d4d19dea62-bluemix:<password_redacted>@44d7fc0c-fa43-48d8-a86e-c4d4d19dea62-bluemix.cloudant.com/fb110773_target",
  "owner": "44d7fc0c-fa43-48d8-a86e-c4d4d19dea62-bluemix",
  "_replication_state": "completed",
  "_replication_state_time": "2018-11-02T00:36:55Z",
  "_replication_id": "5c41510d28d26e691e1466c6e2eb0708",
  "_replication_stats": {
    "revisions_checked": 2,
    "missing_revisions_found": 1,
    "docs_read": 1,
    "docs_written": 0,
    "changes_pending": 1,
    "doc_write_failures": 1,
    "checkpointed_source_seq": "10-g1AAAAGbeJyNz8EKgkAQBuBBhepBOq6406Z1ylfZ2VkxWVcIPdeb1ZvZYkEUhF5mYBi-n98BQFLHDFsm011syYSYUiuMEaydyDA1rhtY-z71tnfhPdJAp3EcmzrW0IbDqqjU8SD3DJvBs63O3vIPKWdIKsOk61uNJlWbwmq2S53vRJnPJPokTLiFFULvny6kkDHH_12kWiQ_XvLUZz3JGZodGrXUap4XVn2S",
    "start_time": "2018-11-02T00:30:11Z"
  }
}
```

**Comment by wohali** [comment]
@brianewilkins please do not hijack this PR with a bug report unless you are specifically reporting a problem **with this PR**.

New bug reports can be filed at https://github.com/apache/couchdb/issues if desired, however this appears to be a Cloudant bug - have you reported it to IBM Support instead?

**Comment by brianewilkins** [comment]
@wohali:
I am IBM Cloudant support and I am the one who reported this issue.
But I doubt that the issue is specific to Cloudant.
I entered the repro here at the request of @nickva.

**Comment by wohali** [comment]
@brianewilkins ok, sorry about that.

@nickva just confirming, you wanted that comment here and not in a new issue?

**Comment by nickva** [comment]
@wohali yeah we had encountered this issue at Cloudant and I suggested @brianewilkins post the scenario to this ticket since we discussed the ticked as related to it. 

Even though the urls contain cloudant.com in them the scenario would be the same for any CouchDB installation. Since @brianewilkins did the work on creating a reproducer script and had a user story behind it thought I it would be good to mention it here.

**Comment by wohali** [comment]
@nickva is this DOA or any chance of trying it again?

**Comment by nickva** [comment]
@wohali  hmm, good question. I am on the fence about it. Probably needs a discussion on the ML. Let's close it for now though.

**Pull request closed without merging**
