### PR TITLE
Add stable and update support to Mango

### LINKED ISSUE #621: Support stable and update options with mango queries
`stable` and `update` options give Mango queries more flexibility in terms of when the results set is updated and whether a fixed replica set is used.

### PR DESCRIPTION
**Pull request by garrensmith**
This brings mango inline with views by supporting the new options
`stable` and `update`.

Fixes #621

## Testing recommendations

See the test for an example on how to test. I'm not really sure of a way to test the `stable` option.

## GitHub issue number

#621

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [x] Documentation reflects the changes; (https://github.com/apache/couchdb-documentation/pull/145)

### CODE REVIEW

**Comment by tonysun83** [comment]
stable and update are replacing stale right? will the same options work for text indexes?

**Comment by garrensmith** [comment]
Yes, those are replacing stale. I'm not sure about text indexes. I don't think so

All misspelling thanks to my iPhone.
________________________________

**Comment by ditta95aR** [comment]
#621

**Comment by janl** [comment]
Please see https://github.com/apache/couchdb/issues/621#issuecomment-315613763 for comment.

**Comment by janl** [comment]
added stale, rebased with master and squashed my commits.

**Comment by tonysun83** [comment]
@garrensmith @janl I like the addition of stale! We'll need to add in support for text indexes for stale as well. This way we are at least trying to be consistent across index options. We may also some logic if the user specifies stable or update for text indexes (which doesn't support that option, but we may already just ignore invalid options). We could move those changes into another PR if this a pressing option we want.

**Comment by davisp** [comment]
+1

@tonysun83 I'd make any changes to the text indexes as new work. I checked and mango_cursor_text will ignore any unknown options so there's no breakage there.

**Comment by tonysun83** [comment]
Sounds good. +1

**Comment by iilyak** [comment]
Merging it in on Garren's behalf since he is on vacation at the moment.

**Pull request merged**
