### PR TITLE
Add ability to configure logger for eunit test step

### PR DESCRIPTION
**Pull request by iilyak**
## Overview

Sometimes it is hard to debug eunit failures. This PR adds an ability to capture logs from the node while running the test case. 

Two environment variables are added to control the behaviour of the logger.

- EUNIT_LOG_FILE - to specify the log file
- EUNIT_LOG_LEVEL - the verbosity level. Which MUST be one of:
  - debug
  - info
  - notice
  - warning
  - error
  - critical
  - alert
  - emergency

If EUNIT_LOG_FILE is not specified the file backend for logger is disabled.

Note:
  The logger is configured only for test cases which use
  `test_util:start_couch` function. If you want to enable
  the logger for other tests you would need to add
  `test_util:maybe_configure_file_logger()` call to `setup`
  function of the test. You also need to make sure that
  the `config` and `couch_log` apps are running.

## Testing recommendations

1. Test without configuring logger 
  - `make eunit apps=couch`
2. Test with configured log file:
  - `EUNIT_LOG_FILE=test_log.log make eunit apps=couch` - check the test_log.log file
  - `EUNIT_LOG_FILE=/tmp/test_log.log make eunit apps=couch` - check the /tmp/test_log.log file
3. Test with configured log file and level 
  - `EUNIT_LOG_FILE=test_log.log EUNIT_LOG_LEVEL=debug make eunit apps=couch`

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by nickva** [comment]
EUnit already logs to files:

```
make eunit apps=mem3
```

```
$ cat ./src/mem3/.eunit/couch.log

...

[error] 2018-10-03T17:42:57.280138Z nonode@nohost <0.137.0> -------- Db was deleted while getting security object. DbName: <<"NoExistDb2">>
[info] 2018-10-03T17:42:57.282706Z nonode@nohost <0.33.0> -------- Application fabric exited with reason: stopped
[info] 2018-10-03T17:42:57.283289Z nonode@nohost <0.33.0> -------- Application mem3 exited with reason: stopped
[info] 2018-10-03T17:42:57.283683Z nonode@nohost <0.33.0> -------- Application rexi exited with reason: stopped
...
```

Log level and other parameters can be configured in: ```./rel/files/eunit.ini```

**Comment by iilyak** [comment]
The default log level for `./rel/files/eunit.ini` is `none`. In order to debug eunit the one have to 
- update the config file
- know which application the test is located to look for log file

This PR adds ability to use env variables to enable logging which is easier compared to editing the file. 
I am happy to close the PR since it is a bit redundant feature.

**Comment by nickva** [comment]
> The default log level for ./rel/files/eunit.ini is none.

In the recent master I see it has

```
[log]
; log to a file to save our terminals from log spam
writer = file
file = couch.log
level = info
```

And most crashes would be caught at level `error` anyway.

In the test run above, I didn't tweak or modify the .ini file and it logged progress well enough. Do you have something locally which attempts to modify the file before running tests?

> know which application the test is located to look for log file

That part is kind of annoying, agree. I would be nice to have one single file to look at and not have to fish through .eunit folders.

@eiri already approved and I'm +0.5 on it. If you think it's helpful go ahead and merge it

**Comment by eiri** [comment]
> It would be nice to have one single file to look at and not have to fish through .eunit folders.

Basically this is why I also +0.5 on this change, which gives it a whole +1 😉

**Comment by iilyak** [comment]
Closing it as redundant.

**Pull request closed without merging**
