### PR TITLE
Support uri_file write for chttpd

### PR DESCRIPTION
**Pull request by KangTheTerrible**
## Overview

The uri_file config parameter was not supported in the switch to chttpd. Pulling the relevant section of code in from couch_sup.erl.

## Testing recommendations
Booting up couchdb with specific cluster port set and port 0.

### CODE REVIEW

**Comment by KangTheTerrible** [comment]
This duplicated block of code still exists in couch_sup.erl and I feel it should be removed.

**Comment by janl** [comment]
> This duplicated block of code still exists in couch_sup.erl and I feel it should be removed.

+1

the rest looks good, well done :)

**Comment by bessbd** [comment]
@janl : should we merge this?

**Comment by janl** [comment]
@bessbd yes :)

**Comment by bessbd** [comment]
Thank you for the patch, @KangTheTerrible and thank you for the review, @janl ! I'm about to merge this.

**Pull request merged**
