### PR TITLE
allow further TLS configuration of clustered port

### PR DESCRIPTION
**Pull request by rnewson**
## Overview

Allow configuration of signature algorithms and allowed ECC curves

## Related Issues or Pull Requests

closes https://github.com/apache/couchdb/issues/5211

## Checklist

- [x] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] Documentation changes were made in the `src/docs` folder
- [ ] Documentation changes were backported (separated PR) to affected branches

### CODE REVIEW

**Review by big-r81 — APPROVED** [review]
Nice!

+1

**Comment by big-r81** [comment]
@rnewson Should we add some sensitive and safe defaults in `default.ini`?

**Comment by rnewson** [comment]
No, I think let erlang/OTP version + mochiweb determine the default, and then a simple override.

We could submit a PR to mochiweb though, its defaults and notion of what is currently "safe" or not "broken" is quite out of date: https://github.com/mochi/mochiweb/blob/611254eb941e502227f221667389b98fd8e72d6f/src/mochiweb_socket.erl#L58

**Review by nickva — APPROVED** [review]

**Comment by nsthakur7** [comment]
Thank you, Robert for actioning the fix so quickly. Can you please let me know, when this fix will be released and which version(s) of couchDB have this fix?

**Pull request merged**
