### PR TITLE
Drop Erlang R16 support

### PR DESCRIPTION
**Pull request by janl**

### CODE REVIEW

**Comment by wohali** [comment]
1) remove [this line](https://github.com/apache/couchdb/blob/master/.travis.yml#L10) from `.travis.yml`
2) this breaks Jenkins, because [Step 1](https://github.com/apache/couchdb/blob/master/Jenkinsfile#L40-L69) (which builds the `dist` tarball) runs in `couchdbdev/ubuntu-trusty-erlang-default` which is `16B03`.

I need to build a new Docker container that has R17 in it instead, a `couchdbdev/ubuntu-trusty-erlang-17.XX.XX` using packages from erlang-solutions. This will be minor changes to [apache/couchdb-ci](https://github.com/apache/couchdb-ci/tree/master/bin) and a `docker push` after the fact.

Please hold on merging this until that's done and I can run a jenkins test. I hope to get to it later today.

**Comment by janl** [comment]
> Please hold on merging this until that's done and I can run a jenkins test.

You’ve got it.

**Comment by janl** [comment]
> remove this line from .travis.yml

Done.

**Comment by wohali** [comment]
@janl I'm building the image today - and will do a separate push to an updated Jenkinsfile to master so that this PR won't break the build. I'll update back when ready.

+1 to dropping 16B03* support.

**Comment by wohali** [comment]
We'll make it for 2.2.0.

**Comment by wohali** [comment]
Once #1438 lands this can merge.

**Comment by wohali** [comment]
As to the discussion part, I know @rnewson was ready to drop 16B03 a long while ago, and there was general agreement on IRC that this is "the right thing to do." Since packages no longer rely on the system-provided Erlang, there is little motivation for us to support really old Erlangs anyway...but shifting to a "you need {latest|latest-1} Erlang release" approach is probably best saved for a 3.0 IMO.

**Comment by nickva** [comment]
+1

**Pull request merged**
