### PR TITLE
Update deps for chttpd and couch app

### PR DESCRIPTION
**Pull request by eiri**
This points to the head of both couch-chttpd and couchdb-couch repos to make travis passable for new commits, as tests of the both repos depends on been in sync after CORS refactoring.

### CODE REVIEW

**Comment by kxepal** [comment]
I would do incremental update one commit per feature. This will simplify searches if something went wrong.

**Comment by eiri** [comment]
Hm. chttpd is seven commits behind, same for couchdb-couch. That makes 3 "features" on couch and 2 on chttpd, as I eyeball git logs. Do you really want 5 separate PRs, consider that this one just became travis green? I mean I can do it, just asking if this is necessary.

**Comment by kxepal** [comment]
No, actually here we have two features: one CORS that updates both couch and chttpd, one fix EPI on chttpd. One PR with two commits is fine.

**Comment by eiri** [comment]
Well, not two, but three, but who's counting, who's counting... ;)

Here we go - one commit per feature.

**Comment by kxepal** [comment]
Oh, I didn't check what previous merge contained. Thanks! +1

**Comment by kxepal** [comment]
Oh, wait, could you include "da860981c9718ba3a119236edcb01d1b4ad85d65" for replicator in " 	Remove configurable replicator db name"?

**Comment by eiri** [comment]
Good catch. We sure need something more reliable than wetware to handle this stuff.

**Pull request merged**
