### PR TITLE
Fix node-specific shard access via HTTP

### LINKED ISSUE #2500: Cannot access individual shard through /_node/{node-name}/shard-path URL
@rnewson I tried all variants but can't get this to work...

```
$ dev/run -n 1 -a admin:password >/dev/null &
# wait a few seconds, then...
$ curl -X PUT http://admin:password@localhost:15984/abc
{"ok":true}
$ ls dev/lib/node1/data/shards/00000000-7fffffff
abc.1580273428.couch              _replicator.1580273362.couch
_global_changes.1580273362.couch  _users.1580273361.couch
$ curl http://admin:password@localhost:15984/_node/_local/_all_dbs
["_dbs","_nodes","_users","shards/00000000-7fffffff/_global_changes.1580273362","shards/00000000-7fffffff/_replicator.1580273362","shards/00000000-7fffffff/_users.1580273361","shards/00000000-7fffffff/abc.1580273428","shards/80000000-ffffffff/_global_changes.1580273362","shards/80000000-ffffffff/_replicator.1580273362","shards/80000000-ffffffff/_users.1580273361","shards/80000000-ffffffff/abc.1580273428"]
$ curl http://admin:password@localhost:15984/_node/_local/abc
{"error":"not_found","reason":"no_db_file"}
$ curl http://admin:password@localhost:15984/_node/_local/shards/00000000-7fffffff/abc.1580273428
{"error":"not_found","reason":"no_db_file"}
$ curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580273428
{"error":"not_found","reason":"no_db_file"}
```

### PR DESCRIPTION
**Pull request by wohali**
## Overview

In #2336 we removed node-local HTTP access and redirected all traffic through `/_node/{node-name}/...`. This sneakily routes a new MochiWeb request through to couch_httpd under the covers.

Unfortunately, in the process we ended up URL-decoding the URL, meaning the passed-through URL couldn't include `%2F` for accessing individual shards.

This reintroduces URL encoding to fix the problem.

It also introduces support to query a specific view shard through `/_node/{node-name}/{db-shard}/{ddoc}/`. This allows inspection of individual view shard sizes.

## Testing recommendations

```
dev/run -n 1 -a admin:password
curl -X PUT http://admin:password@localhost:15984/abc
curl -X PUT http://admin:password@localhost:15984/abc/_design%2ffoo -d '{"language":"javascript","views":{"all":{"map":"function(doc) { emit(doc._id, null);}"}}}'
curl -X PUT http://admin:password@localhost:15984/abc/def -d '{}'
curl -X PUT http://admin:password@localhost:15984/abc/qqq -d '{}'
curl http://admin:password@localhost:15984/_node/_local/_all_dbs
# substitute your timestamp code in the following lines...
curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580273428
curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580273428/def
curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580273428/qqq

curl http://admin:password@localhost:15984/abc/_design/foo/_info
curl http://admin:password@localhost:15984/abc/_design/foo/_view/all
curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580273428/_design/foo/_info
curl http://admin:password@localhost:15984/_node/_local/shards%2f80000000-ffffffff%2fabc.1580273428/_design/foo/_info
curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580273428/_design/foo/_view/all
curl http://admin:password@localhost:15984/_node/_local/shards%2f80000000-ffffffff%2fabc.1580273428/_design/foo/_view/all
```

Example output for the last few lines (new per-view-shard endpoint):

```
$ curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580515057/_design/foo/_info
{"name":"foo","view_index":{"signature":"de76da589940694f05807f0c4fb5d33a","language":"javascript","sizes":{"file":4190,"active":98,"external":24},"update_seq":1,"purge_seq":0,"update_options":[],"updater_running":false,"compact_running":false,"waiting_commit":false,"waiting_clients":0,"pending_updates":0}}
$ curl http://admin:password@localhost:15984/_node/_local/shards%2f80000000-ffffffff%2fabc.1580515057/_design/foo/_info
{"name":"foo","view_index":{"signature":"de76da589940694f05807f0c4fb5d33a","language":"javascript","sizes":{"file":8292,"active":98,"external":24},"update_seq":2,"purge_seq":0,"update_options":[],"updater_running":false,"compact_running":false,"waiting_commit":false,"waiting_clients":0,"pending_updates":0}}

$ curl http://admin:password@localhost:15984/_node/_local/shards%2f00000000-7fffffff%2fabc.1580515057/_design/foo/_view/all
{"total_rows":1,"offset":0,"rows":[
{"id":"def","key":"def","value":null}
]}
$ curl http://admin:password@localhost:15984/_node/_local/shards%2f80000000-ffffffff%2fabc.1580515057/_design/foo/_view/all
{"total_rows":1,"offset":0,"rows":[
{"id":"qqq","key":"qqq","value":null}
]}

```

## Related Issues or Pull Requests

Closes #2500 fully.

### CODE REVIEW

**Comment by wohali** [comment]
@nickva For posterity, as I said on IRC, this endpoint is only to support what we need for admin purposes. Right now that's inspecting the top-level of a shard, as well the system databases. I'd like to add support for looking at view shard _info objects, but it's not a 3.0 blocker.

What I'll do is see if we can just return an error when trying to retrieve attachments via this interface, rather than trying to support them for unknown purposes.

Tomorrow.

**Comment by nickva** [comment]
@wohali pushed a fix, it turned out not as bad as I suspected

```
http  $DB/_node/_local/shards%2f80000000-ffffffff%2fdeebee.1580329759/dok2/att1

{
    "x": "y"
}
```

**Comment by wohali** [comment]
Going to hold this for another 1-2 days to see if I can't get in the ability to inspect specific view shards, not just the view shard that hosts the ddoc itself. If I can't manage that, I'll merge this as is.

**Comment by wohali** [comment]
Big thanks to @kocolosk who nudged me in the right direction on IRC for per-view-shard endpoint exposure. Like @nickva 's change, it turned out to be very little code to support this.

**Pull request merged**
