### PR TITLE
Bump recon to 2.5.3

### PR DESCRIPTION
**Pull request by nickva**
Changes since 2.5.2: https://github.com/ferd/recon/compare/2.5.2...2.5.3

### CODE REVIEW

**Review by big-r81 — APPROVED** [review]
+1

**Comment by OlekMazur** [comment]
Hi,

I have a problem configuring couchdb at Fedora 38 which seems related to recon 2.5.3:
```
Updating recon from {git,"https://github.com/apache/couchdb-recon.git",
                         {tag,"2.5.3"}}
error: pathspec '2.5.3' did not match any file(s) known to git
ERROR: sh(git checkout -q 2.5.3)
failed with return code 1 and the following output:
error: pathspec '2.5.3' did not match any file(s) known to git
```

https://github.com/apache/couchdb-recon/tree/2.5.3 shows "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

But when I switched remote "origin" url in src/recon/.git/config from https://github.com/apache/couchdb-recon.git to https://github.com/ferd/recon.git , configure script succeeded.

Looks like you can't checkout 2.5.3 out of apache/couchdb-recon.git repo (?)

**Comment by nickva** [comment]
Hi Aleksander,

I think might have forgotten to push the upstream master changes to our couchdb main clone and the changes were only on the tag. In that case the change appeared only on the tag (release), maybe that would have been the issue. I just updated couchdb main and tried making a new clone of couchdb and ran configure it seems to have correctly fetched the latest recon.

```
Updating recon from {git,"https://github.com/apache/couchdb-recon.git",  {tag,"2.5.3"}}
```

See if you give it another try if it would work?

**Comment by big-r81** [comment]
@nickva 

Didn’t we use upstream directly?

**Comment by OlekMazur** [comment]
The warning at https://github.com/apache/couchdb-recon/tree/2.5.3 I mentioned before disappeared, and after deleting src/recon the ./configure script was able to pull it automatically, so the problem is gone. Thanks.
```
==> couchdb (get-deps)
Pulling recon from {git,"https://github.com/apache/couchdb-recon.git",
                        {tag,"2.5.3"}}
Klonowanie do „recon”...
==> recon (get-deps)
==> couchdb (update-deps)
```

**Comment by nickva** [comment]
@big-r81 not entirely sure, we were able to do the clone and run CI all this time (which builds a full release off of main) and we obviously ran ./configure --dev on main many times before. In some environments git may complain more if the tagged commits are also on a branch somewhere, perhaps...

**Pull request merged**
