### PR TITLE
Fix boolean POST to view-like endpoints

### PR DESCRIPTION
**Pull request by bessbd**
This is a backport of #3201

### CODE REVIEW

**Review by jjrodrig — APPROVED** [review]
Hi @bessbd 
+1 since it is already merged into master

Please, could you update with the latest 3.x changes?

**Comment by bessbd** [comment]
Thank you for the review, @jjrodrig ! If you meant a rebase on `3.x`, then I just did that. Can you please merge this PR for me?

**Comment by jjrodrig** [comment]
Thanks @bessbd

**Comment by bessbd** [comment]
Thank you for the merge, @jjrodrig !

**Pull request merged**
