### PR TITLE
Add recommended docs section

### PR DESCRIPTION
**Pull request by robertkowalski**
Most people don't program a database and many do not work on distributed systems.

The idea is to lower the entry barrier to CouchDB and the concepts behind it. Many possible committers and newcomers are new to database development and distributed systems.

inspired by https://twitter.com/ag_dubs/status/721874316183396352

### CODE REVIEW

**Comment by kxepal** [comment]
I think we should recommend (if so) docs that describes technologies used by CouchDB. Otherwise it will not lower, but only raise entry barrier and cause a lot of confusions. For instance, `The Ubiquitous B-Tree` paper is interesting, but shouldn't we describe CouchDB implementation instead? Amazon’s HA Key-value Store - hey, I want to learn how CouchDB works, not some else KV storage I will not use. And so on.

Also all these resources are for database / distributed-systems developers. Unless we suggest our users to get at the such lower level, I think they would better learn how HTTP and map/reduce works since these two things are the first what they'll meet in CouchDB.

**Comment by michellephung** [comment]
this is a good idea. we can expand to more links as people find them.

**Comment by garrensmith** [comment]
I really like this idea. I think a mixture of general distributed systems reading and CouchDB reading would be cool. I would keep the info you have here already and then add some CouchDB related docs.

**Comment by janl** [comment]
I also like this idea.

**Pull request closed without merging**
