### PR TITLE
Blacklist some config sections from HTTP PUT/DELETE operations

### PR DESCRIPTION
**Pull request by wohali**
Covers clustered and node-local ports.

Includes JS test for clustered port.

### CODE REVIEW

**Comment by ondra-novak** [comment]
Is there some way to remove blacklist? I am heavily using os_daemons to start/stop daemons by http

**Comment by kxepal** [comment]
@ondra-novak 
Suddenly, no - it's a security measurement. However, for 2.x you still can manage os_daemons in runtime by modifying config file and reloading it via `/_config/_reload`, IIRC. You can setup special externals which will do that for you.

**Comment by ondra-novak** [comment]
OK, so I will need to put some http server there.... 

```
<irony>oh boy, please make things more complicated later</irony>
```

**Comment by wohali** [comment]
We know this change is frustrating for your specific use case, but there is a good reason for this change.

Again, insulting members of our project team doesn't help anyone. I ask you again to abide by our [Code of Conduct](https://couchdb.apache.org/conduct.html).

**Pull request merged**
