### PR TITLE
Avoid scanning functions with non-deterministic behavior

### PR DESCRIPTION
**Pull request by nickva**
A large number of false positives seen so far have to deal with users using `Date.now()` or `Math.random()` in the map or reduce function bodies. Needless to mention those will always produce false positive results.

Attempt a heuristic approach to avoid scanning views which contain the most common sources of determinism found so far. These include current date fetching and `Math.random()`.

### CODE REVIEW

**Review by rnewson — APPROVED** [review]
🙃

**Comment by pgj** [comment]
Would not it be possible to make those problematic functions deterministic for the scanning?  Something along the lines of mocking the date and random functions to provide the same of values, so that the engine would run the same code with the same input.  If the sequence of pseudorandom values is seeded with the actual date and time, maybe it is enough to fixate that only.

**Comment by nickva** [comment]
@pgj good idea in general, but not sure how we'd do that in our case across two different javascript engines from Erlang.

**Comment by pgj** [comment]
I am not (yet) familiar with the internals of SpiderMonkey and QuickJS.  I was thinking about finding the right API calls or interface elements that would allow us to seed the JS engine with a specific state for example.  Maybe that is not trivial or maybe this is not how the engines are integrated.

**Comment by pgj** [comment]
There are of course solutions like [`faketime`](https://github.com/wolfcw/libfaketime) which are application-agnostic.

**Comment by nickva** [comment]
Ah, very nice! `LD_PRELOAD` is such a neat trick.

**Pull request merged**
