### PR TITLE
Let's see if we can re-enable s390x again

### PR DESCRIPTION
**Pull request by nickva**
Previously it had issues downloading from hex.pm

### CODE REVIEW

**Comment by nickva** [comment]
Interestingly enough, re-enabling s390x now shows a discrepancy in the new fast_pbkdf2 module on s390x:

```
[2024-01-16T17:51:39.919Z]   module 'couch_passwords_tests'
[2024-01-16T17:51:39.919Z]     PBKDF2
[2024-01-16T17:51:39.919Z]       couch_passwords_tests:20: pbkdf2_test_ (Iterations: 1, length: 20)...*failed*
[2024-01-16T17:51:39.919Z] in function couch_passwords_tests:'-pbkdf2_test_/0-fun-1-'/0 (test/eunit/couch_passwords_tests.erl, line 22)
[2024-01-16T17:51:39.919Z] in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71)
[2024-01-16T17:51:39.919Z] in call from eunit_proc:run_test/1 (eunit_proc.erl, line 531)
[2024-01-16T17:51:39.920Z] in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 356)
[2024-01-16T17:51:39.920Z] in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 514)
[2024-01-16T17:51:39.920Z] in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 456)
[2024-01-16T17:51:39.920Z] in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 346)
[2024-01-16T17:51:39.920Z] in call from eunit_proc:run_group/2 (eunit_proc.erl, line 570)
[2024-01-16T17:51:39.920Z] **error:{assertEqual,[{module,couch_passwords_tests},
[2024-01-16T17:51:39.920Z]               {line,22},
[2024-01-16T17:51:39.920Z]               {expression,"couch_passwords : pbkdf2 ( << \"password\" >> , << \"salt\" >> , 1 , 20 )"},
[2024-01-16T17:51:39.920Z]               {expected,<<"0c60c80f961f0e71f3a9b524af6012062fe037a6">>},
[2024-01-16T17:51:39.920Z]               {value,<<"f35fbe4aae65fbc6f43df01e6bb6c86f9f75db74">>}]}
[2024-01-16T17:51:39.920Z]   output:<<"">>
[2024-01-16T17:51:39.920Z] 
[2024-01-16T17:51:39.920Z]       couch_passwords_tests:26: pbkdf2_test_ (Iterations: 2, length: 20)...*failed*
```

**Comment by rposts** [comment]
@nickva I will get someone from my team to look into it as well - tx!

**Comment by nickva** [comment]
Thank you, @rposts. It might endianness related.

Since last time we ran the CI worker we included this library: https://github.com/esl/fast_pbkdf2/blob/main/c_src/fast_pbkdf2.c I wonder if it just make an implicit assumption that it's handling little endian data always.

**Comment by big-r81** [comment]
Could [this](https://github.com/esl/fast_pbkdf2/blob/d079c45a5a9b9d6c9158a8082e7329de5a0b38fb/c_src/fast_pbkdf2.c#L41) and [this](https://github.com/esl/fast_pbkdf2/blob/d079c45a5a9b9d6c9158a8082e7329de5a0b38fb/c_src/fast_pbkdf2.c#L53) be the reason?

**Comment by nickva** [comment]
That looks plausible, thanks for taking a look, @big-r81

**Comment by namrata-ibm** [comment]
@nickva The issue in fast_pbkdf2 is endianness related. With a few changes in it, `couch_passwords_tests` passed on an s390x system. I am working on adding the changes via PR to fast_pbkdf2. Thank you.

**Comment by namrata-ibm** [comment]
@nickva @big-r81 The issue with fast_pbkdf2 has been resolved via [PR](https://github.com/esl/fast_pbkdf2/pull/12).
Wanted to know how those changes are picked up here? Is fast_pbkdf2 is updated on regular basis?

**Comment by big-r81** [comment]
Hey @namrata-ibm, you update the files from upstream like [here](https://github.com/apache/couchdb/commit/42c24843e2759144381b8c2ae80dd2a003ccc899).

**Comment by big-r81** [comment]
and we should wait until https://github.com/esl/fast_pbkdf2/pull/13 is merged.

**Comment by NelsonVides** [comment]
Fast-PBKDF2 all merged and new release created: https://hex.pm/packages/fast_pbkdf2/1.0.6, thanks for the contributions :)

**Comment by nickva** [comment]
I noticed one successful run on s390x!

Screenshot 2024-01-26 at 6 54 09 PM

I'll restart it to see a get a few more successful run.

**Comment by big-r81** [comment]
This looks good. Thanks @namrata-ibm and @NelsonVides for your support.

**Comment by nickva** [comment]
There were 4 successful CI runs in row, so it looks quite promising. I'll merge the PR.

**Pull request merged**
