### PR TITLE
Re-enable more elixir tests

### PR DESCRIPTION
**Pull request by bessbd**
## Overview
The only test in the group is passing. This PR re-enables it.

## Checklist

- [ ] Code is written and works correctly
- [ ] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Review by jaydoane — CHANGES_REQUESTED** [review]
This test is unfortunately still failing for me and the CI:
```
09:10:44  CookieAuthTest
09:10:45    * test cookie auth
  * test cookie auth (210.5ms)
09:10:45  
09:10:45    1) test cookie auth (CookieAuthTest)
09:10:45       test/elixir/test/cookie_auth_test.exs:208
09:10:45       Expected truthy, got false
09:10:45       code: assert Enum.member?(info["userCtx"]["roles"], "foo")
09:10:45       arguments:
09:10:45  
09:10:45           # 1
09:10:45           []
09:10:45  
09:10:45           # 2
09:10:45           "foo"
09:10:45  
09:10:45       stacktrace:
09:10:45         test/elixir/test/cookie_auth_test.exs:376: (test)
09:10:45  
```

On a happy note, this one passes:
```
CopyDocTest
  * test Copy doc tests (90.0ms)
```

**Comment by bessbd** [comment]
> This test is unfortunately still failing for me and the CI:
> 
> ```
> 09:10:44  CookieAuthTest
> 09:10:45    * test cookie auth
>   * test cookie auth (210.5ms)
> 09:10:45  
> 09:10:45    1) test cookie auth (CookieAuthTest)
> 09:10:45       test/elixir/test/cookie_auth_test.exs:208
> 09:10:45       Expected truthy, got false
> 09:10:45       code: assert Enum.member?(info["userCtx"]["roles"], "foo")
> 09:10:45       arguments:
> 09:10:45  
> 09:10:45           # 1
> 09:10:45           []
> 09:10:45  
> 09:10:45           # 2
> 09:10:45           "foo"
> 09:10:45  
> 09:10:45       stacktrace:
> 09:10:45         test/elixir/test/cookie_auth_test.exs:376: (test)
> 09:10:45  
> ```
> 
> On a happy note, this one passes:
> 
> ```
> CopyDocTest
>   * test Copy doc tests (90.0ms)
> ```

Yeah, I'm working on it. It was passing locally for me so now I'm trying to figure out if I'll add some polling or if I need to rewrite the test case a bit. Thank you for the review, @jaydoane !

**Comment by bessbd** [comment]
@jaydoane : I've added a retry and CI seems happy now

**Review by jaydoane — APPROVED** [review]
```
CookieAuthTest
  * test cookie auth (1147.3ms)
```
Nice! Seems like that did the trick. Just a good ol' race condition.

**Comment by bessbd** [comment]
Thank you for the review, @jaydoane ! I'm about to merge this.

**Pull request merged**
