### PR TITLE
Fix Makefile, finish separation of CouchDB/Fauxton compilation

### PR DESCRIPTION
**Pull request by candeira**

### CODE REVIEW

**Comment by kxepal** [comment]
`javascript` target still depends on `compile`.

**Comment by candeira** [comment]
Groan. You're right. Fixed.

**Comment by kxepal** [comment]
Landed!

**Comment by candeira** [comment]
Hi @kxepal, I'm guessing that github says "Closed with unmerged commmits" because you picked the PR directly from the ASF git repo. Where is that workflow documented?

**Comment by kxepal** [comment]
There isn't. There is no need to produce merges on master branch for small fixes. It's makes a sense when it is release branch or you develop some feature with many commits, so merge makes easily to track the from where the changes came from.

**Pull request closed without merging**
