### PR TITLE
COUCHDB-769: Store attachments in the external storage

### PR DESCRIPTION
**Pull request by gilv**
Initial implementation that allows CouchDB to store attachments outside of the database file.
This implementation supports OpenStack Swift and SoftLayer Object store.

### CODE REVIEW

**Comment by rnewson** [comment]
noting here that we shouldn't merge this work (or any new significant feature work) before 2.0.

**Comment by gilv** [comment]
@rnewson : i updated master branch, then merged it with my branch and pushed the changes.
It seems the merge is a bit weird.. can you explain me what i did wrong?
Here is what i did:

git remote -v
origin	https://github.com/gilv/couchdb.git (fetch)
origin	https://github.com/gilv/couchdb.git (push)
upstream	https://github.com/apache/couchdb.git (fetch)
upstream	https://github.com/apache/couchdb.git (push)

git checkout master
git pull upstream master
git push
git checkout store_attachments_external
git fetch origin
git merge origin/master

when  i did: 
git push origin store_attachments_external  - there was an error that i should pull before.
so i did: 
git pull origin store_attachments_external
and then 
git push origin store_attachments_external

Now i see that something is wrong and there are commits that has nothing to do to my code

**Comment by gilv** [comment]
@rnewson i got it... it was my mistake, when i did git pull..
so my question now is : is it fine that it shows 25 commits when actually i have only one here?

**Comment by gilv** [comment]
@kxepal @rnewson 
I provided another patch, implementing most of the comments.
Here is what is not implemented in this patch:

1.  Remark on the AttFun. Not yet implemented. Original remark:  “AttFun could be actually an attachment data or some fold function? Something went wrong if you have to do this.” 
2.  usage of  couch_util:to_hex
3.  still no unitests

**Comment by wohali** [comment]
Hi @rnewson and @davisp , is this affected at all by the pluggable storage engine work? (I'm guessing it might very well be.) If not, could we consider merging it?

**Comment by rnewson** [comment]
yes, would be affected (i.e, broken)

**Comment by davisp** [comment]
Stil on my phone but all I'm seeing is a diff in a config file which whie harmless suggests either the pr or my phone is broken.

**Comment by wohali** [comment]
@gilv this patch is outdated. I'm going to close this PR for now. We'd love to have you rebase this against CouchDB 2.0 and re-submit -- please do! Thanks for your contribution to CouchDB.

**Pull request closed without merging**
