### PR TITLE
Enable coverage reports for more applications

### PR DESCRIPTION
**Pull request by nickva**
Previously because of an outdated meck version coverage analysis had to be
disabled for some modules.

### CODE REVIEW

**Comment by eiri** [comment]
But do we really want coverage to be always enabled? It's going to be executing on each travis run, adding to a running time and making logs even less readable and it's not even actionable item - it doesn't really affect review process, more like curiosity and test strategy driving metrics, not part of CI pipe.

What I'm trying to say, if that's possible, I'd personally prefer to have coverage functionality ad-hoc, as a part of `make` command.

**Comment by nickva** [comment]
It was already running for a few apps and didn't seem to add too much overhead.

Is there is a easy way to toggle it on and off without having a rebar.config.script or something like that.

**Comment by eiri** [comment]
It's running for couch_epi and couch_log, I believe, for both because they've been build from a scratch, test cover was usable for development and then got included as a part of a bigger merge, not because it was turned on exclusively. We don't know how much overhead that adds, because we never measured it :)

My point thought not about performance penalty per se, but about unnecessary movement. In CI the generated reports not visible and not easily accessible, apart from scrolling the endless log, so it's not really helpful to have them always on.

In general I'm +0 on this change. If you get +1 from someone I wouldn't block it, our test suite already bulky and verbose, adding coverage not going to change things dramatically.

I don't know easy way to make rebar switch cover, sorry :/ In rebar3 it is a separate command, which makes sense for me, but our rebar, I'm afraid, would require script trickery.

**Comment by nickva** [comment]
I saw a consistent failure on 16 and 17 in one of the tests. Closing it for now, will investigate it later.

**Pull request closed without merging**
