### PR TITLE
Fix the ability to use ; in config values

### PR DESCRIPTION
**Pull request by nickva**
Config values may contain `;` in them as long as `;` is not preceded by a space or a tab character.

Fixes: https://github.com/apache/couchdb/issues/4651

This regression was introduced in: https://github.com/apache/couchdb/pull/4287

### CODE REVIEW

**Comment by mohmesflir** [comment]
The string of ; separated values that I have been using do not have a space or tab preceding the ;.  So this is not working in 3.3.x.

**Comment by mohmesflir** [comment]
It does work in versions prior to and including 3.2.3 but not in 3.3.1 or 3.3.2

**Review by rnewson — APPROVED** [review]
oops

**Comment by nickva** [comment]
> The string of ; separated values that I have been using do not have a space or tab preceding the ;. So this is not working in 3.3.x.

That makes sense. The PR should fix it. If you're able to compile and make release yourself let us know if it work. 

Thanks for reaching out and reporting the issue.

**Pull request merged**
