### PR TITLE
Add Erlang 25 to PR CI pipeline and Ubuntu Jammy to full CI

### PR DESCRIPTION
**Pull request by nickva**

### CODE REVIEW

**Comment by nickva** [comment]
For some reason still getting

```
[2022-07-03T20:25:42.978Z] ==> rel (compile)
[2022-07-03T20:25:42.978Z] ==> ****-cm1_PullRequests_PR-4086 (compile)
[2022-07-03T20:25:43.719Z] warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
[2022-07-03T20:25:44.066Z] 
[2022-07-03T20:25:44.066Z] 20:25:43.844 [error] beam/beam_load.c(86): Error loading module 'Elixir.Code.Formatter':
[2022-07-03T20:25:44.066Z]   lambda already defined for label 749. To fix this, please recompile this module with an OTP 25 compiler.
[2022-07-03T20:25:44.066Z] 
[2022-07-03T20:25:44.066Z] 
[2022-07-03T20:25:44.066Z] 
[2022-07-03T20:25:44.066Z] 20:25:43.844 [error] Loading of /usr/local/bin/../lib/elixir/ebin/Elixir.Code.Formatter.beam failed: :badfile
[2022-07-03T20:25:44.066Z] 
[2022-07-03T20:25:44.066Z] ** (UndefinedFunctionError) function Code.Formatter.locals_without_parens/0 is undefined (module Code.Formatter is not available)
[2022-07-03T20:25:44.066Z]     (elixir 1.13.4) Code.Formatter.locals_without_parens()
[2022-07-03T20:25:44.066Z]     (elixir 1.13.4) lib/code/normalizer.ex:22: Code.Normalizer.normalize/2
[2022-07-03T20:25:44.066Z]     (elixir 1.13.4) lib/code.ex:1107: Code.quoted_to_algebra/2
[2022-07-03T20:25:44.066Z] make[1]: *** [Makefile:247: elixir-init] Error 1
[2022-07-03T20:25:44.066Z] make[1]: Leaving directory '/home/****/workspace/****-cm1_PullRequests_PR-4086'
[2022-07-03T20:25:44.066Z] make: *** [Makefile:155: check] Error 2
```

Even after building an image with bullseye erlang 25.0.2 and downloading the pre-compiled Elixir 1.13.4 for OTP 25 it still shows the error.

**Comment by big-r81** [comment]
Maybe we should try to compile Elixir by ourselves with the use of `kiex` to test that's not a problem with the binary?

**Comment by nickva** [comment]
@big-r81 good idea to try. I 

I had tried to remove as many things from `Jenkinsfile.pr` as possible to see if the problem would still occur. Interestingly I cannot make it fail locally with the same image so it makes me think there is something silly in the Jenkins pipeline.

It's as if it using a cached version of the 25.0.2 docker image I had uploaded first, which didn't have OTP 25 compiled Elixir beam files. Another idea is that the Jenkins matrix build and sharing of workspaces somehow makes the builds see each other's Elixir beams (the workspaces are not totally isolated) so we end up reading older beam files.

Next I was going to disable the matrix build and build just for the 25.0.2 and then try to load the beam file in the Erlang interpreter in Jenkins and make it output the compiler details to see if it's actually compiled with OTP 25 or not (it would detect using the old version of the image).

**Comment by nickva** [comment]
It seems as if we're running with the wrong docker image.

I had added a debug print of the beam file which is supposedly "bad" in the Jenkins job for 25.0.2 image.

Locally it prints:
```
erl -noshell -eval '{ok, F} = file:read_file("/usr/local/lib/elixir/ebin/Elixir.Code.Formatter.beam"), {ok, Info} = beam_lib:chunks(F, [compile_info, attributes]), erlang:display(Info), halt().'

{'Elixir.Code.Formatter',[{compile_info,[
  {version,"8.2"},{options,[no_spawn_compiler_process,from_core,no_core_prepare,no_auto_import]}, 
  {source,"/home/build/elixir/lib/elixir/lib/code/formatter.ex"}]},
  {attributes,[{vsn,[212914653288359122158021616057205722824]}]}]}
```

and on Jenkins it prints
```
[2022-07-05T00:38:30.257Z] + erl -noshell -eval {ok, F} = file:read_file("/usr/local/lib/elixir/ebin/Elixir.Code.Formatter.beam"), {ok, Info} = beam_lib:chunks(F, [compile_info, attributes]), erlang:display(Info), halt().

[2022-07-05T00:38:30.257Z] {'Elixir.Code.Formatter',[{compile_info,[
   {version,"7.5.4"},{options,[no_spawn_compiler_process,from_core,no_core_prepare,no_auto_import]},{source,"/Users/jose/OSS/elixir/lib/elixir/lib/code/formatter.ex"}]},
{attributes,[{vsn,[29502098686927955986765935609998676965]}]}]}
```

But now I am wondering how we ended up with that outdated file/image...

**Comment by nickva** [comment]
@big-r81 well it does seem it cached the docker image somehow. To "fix" it I deleted the bullseye 25.0.2 image from docker and re-created it.

The long version is I  created a new PR for the CI test only (a new branch) after I deleted the tag from docker. and noticed that it  ran successfully (!).  Which is bonkers because the image from docker hub with that tag should have been removed. And I was expecting an error that it couldn't find the image.

Then I re-built the image from couchdb-ci and pushed it also re-created the CI PR and now everything passes https://github.com/apache/couchdb/pull/4088

So there is some caching and connection to rebuilding the same PR (pushing to the same branch) where it decided to reuse the exact docker image ...?

Anyway I'll close this PR and let's just roll with that other one

**Pull request closed without merging**
