### PR TITLE
Compaction status update

### PR DESCRIPTION
**Pull request by vitaly-goot**
See issue #980 

Extend `_active_tasks` reporting for data compaction. New fields include:
- size in bytes of meta file (reported under @meta_size attribute)
- size in bytes of data file (reported under @data_size attribute)
- timestamp of merge phase or zero (reported under @merged_on attribute)

File size reporting is handy to get statistics about disk burn rate and disk overhead during data compaction. 
It also can be used to understand that compaction process is live (kind of beatheart) since progress is not reported during compaction `merge` phase and compaction appears to be stuck.

### CODE REVIEW

**Comment by vitaly-goot** [comment]
commit `8dac207`:

count number of bb chains during sort phase in emsort;
emsort:get_status returns additional counter (to be saved in compaction meta file)
calculate merge phase progress after merge is started

**Comment by wohali** [comment]
@vitaly-goot Any desire to refresh this one and fix the failed build?

**Comment by vitaly-goot** [comment]
Hi Joan,

Looking at the changes in your master. It's a substantial code change and
refactoring. You just rewrite everything :).

To merge my changes I will need to understand new code. Hopefully will have
time for it in a week or two.

thanks,
-Vitaly

**Comment by wohali** [comment]
You will want to look at the replication scheduler data, for sure. This might be something that, if not already reported, could go in the `info` field of the new endpoint, see #1159 .

**Comment by janl** [comment]
Please re-open with updates.

**Pull request closed without merging**
