### PR TITLE
Add clustered db info

### LINKED ISSUE #1278: Add clustered db info endpoint
When you query db info by way of `GET /dbname`, it returns an aggregated info blob based on the first responding shard replica for each range. We should have a clustered endpoint that returns the full set of shard infos, non aggregated.

Proposed API endpoint:

`GET /dbname/_info`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

### PR DESCRIPTION
**Pull request by janl**
Closes #1278

### CODE REVIEW

**Comment by wohali** [comment]
@janl not sure why tests are failing here, care to take a look?

**Comment by wohali** [comment]
@janl here's the problem:

```
module 'couch_replicator_create_target_with_options_tests'
  Create target with range partitions tests
    undefined
    *** instantiation of subtests failed ***
**in function couch_replicator_create_target_with_options_tests:should_create_target_with_q_4/1 (test/couch_replicator_create_target_with_options_tests.erl, line 61)
**error:{badmatch,{error,{db_not_found,<<"could not open http://127.0.0.1:41783/eunit-test-db-"...>>}}}
```

Maybe something's wrong with `PUT /db` when you specify `?q=#&n=#`?

**Comment by wohali** [comment]
@janl I'm going to continue to keep this out of 2.3.0, as much as I'd like to put it in...if you have time to address in the next few days, I'm receptive to it landing. But the test cases need to be fixed and ideally I'd want a +1 from @chewbranca or @rnewson or similar on the approach.

**Comment by wohali** [comment]
@chewbranca looks like this is your patch. Do you have any time to review this?

While I'm at it, what can we do about the `/{db}/{ddoc}/_info` endpoint to solve the same problem?

**Comment by wohali** [comment]
bump, if anyone wants to take this I'd love to see it land sooner rather than later.

**Comment by wohali** [comment]
really wish we could get this into 3.0. :(

**Comment by wohali** [comment]
@janl Any plans to get this in? I am preparing to mass-close old PRs that never got merged.

**Comment by big-r81** [comment]
Any plans to get this in? Maybe this needs a rebase to `main`?

**Comment by nickva** [comment]
We have implemented something like this which also allows getting multiple db infos:

```
% http $DB/_dbs_info'?key="db1"'

[
    {
        "info": {
            "cluster": {
                "n": 1,
                "q": 2,
                "r": 1,
                "w": 1
            },
            "compact_running": false,
            "db_name": "db1",
            "disk_format_version": 8,
            "doc_count": 0,
            "doc_del_count": 0,
            "instance_start_time": "1666880205",
            "props": {},
            "purge_seq": "0-g1AAAABTeJzLYWBgYMpgTmHgz8tPSTV0MDQy1zMAQsMckEQeC5BkaABS_4EgK5EBp8pEhqR6iJIsACz0Fj4",
            "sizes": {
                "active": 0,
                "external": 0,
                "file": 16696
            },
            "update_seq": "0-g1AAAACTeJzLYWBgYMpgTmHgz8tPSTV0MDQy1zMAQsMckEQeC5BkaABS_4EgK4M5kSEXKMBubmCckmRkhKkLp0mJDEn1KEYYGCcZmiVjMSILABMCI_8"
        },
        "key": "db1"
    }
]
```

**Comment by nickva** [comment]
Closing due to lack of activity and since we already implemented it

**Pull request closed without merging**
